src/main/java/uk/gov/hmcts/reform/civil/model/dq/Applicant1DQ.java, src/main/java/uk/gov/hmcts/reform/civil/model/dq/DQ.java, src/main/java/uk/gov/hmcts/reform/civil/model/dq/Experts.java, src/main/java/uk/gov/hmcts/reform/civil/model/dq/Hearing.java, src/main/java/uk/gov/hmcts/reform/civil/model/dq/Respondent1DQ.java, src/main/java/uk/gov/hmcts/reform/civil/model/dq/Witnesses.java, src/test/java/uk/gov/hmcts/reform/civil/model/dq/Applicant1DQTest.java, src/test/java/uk/gov/hmcts/reform/civil/model/dq/DQTest.java
https://tools.hmcts.net/jira/browse/CMC-1598
Removing:
- experts details
- witnesses details
- hearing unavailable dates
when data was provided, but then changed to not needed (hidden fields in CCD does not remove the data as expected).
```
[ ] Yes
[x] No
```
=> fix: remove experts, witnesses and unavailable dates from case data (CMC-1598)

infrastructure/main.tf
Use send grid api key from civil account instead of damages account.
I did setup a new account on sendGrid for new name of our service civil This PR should use the api key from that account. damages account will be removed later. 
=> tech: use send grid api key from civil account (CMC-1555)

bin/import-bpmn-diagram.sh, src/main/java/uk/gov/hmcts/reform/civil/config/CamundaConfiguration.java, src/main/java/uk/gov/hmcts/reform/civil/service/EventEmitterService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/civil/service/EventEmitterServiceTest.java
=> fix: added tenant id to camunda messages

src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/ClaimDismissedHandler.java, src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/TakeCaseOfflineHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/ClaimDismissedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/TakeCaseOfflineHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1584
Scheduler handlers should now be resilient when handling multiple cases when one errors.
```
[ ] Yes
[x] No
```
=> fix: catch exceptions in scheduler handlers (CMC-1584)

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/AddOrAmendClaimDocumentsCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java, src/main/java/uk/gov/hmcts/reform/civil/model/ServedDocumentFiles.java, src/main/java/uk/gov/hmcts/reform/civil/validation/interfaces/ParticularsOfClaimValidator.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/AddOrAmendClaimDocumentsCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimDetailsCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/model/ServedDocumentFilesTest.java
https://tools.hmcts.net/jira/browse/CMC-1490
- Created a new function in `ParticularsOfClaimValidator` that will validate for addOrAmendClaimDocuments event, as now ParticularsOfClaim document and text are optional (also accounting for backwards compatible code for particulars of claim)
- created tests in `AddOrAmendClaimDocumentsCallbackHandlerTest` (also backwards compatible)
- created tests in `NotifyClaimDetailsCallbackHandlerTest` (also backwards compatible)
- amended tests in `ServedDocumentFilesTest`
( https://github.com/hmcts/civil-damages-ccd-definition/pull/41 merged first)
```
[ ] Yes
[x] No
```
=> feat: changes to add or amend claims logic (CMC-1490) (2/2)

src/main/java/uk/gov/hmcts/reform/civil/model/LitigationFriend.java
https://tools.hmcts.net/jira/browse/CMC-1596
- introducing new code for change of field type of `certificateOfSuitability` from collection of `Document` to collection of `DocumentOrImageWithRegex`
```
[ ] Yes
[x] No
```
=> fix : backwards compatible new field type for certificate of suitability on litigation friend event (CMC-1596) (1/5)

Jenkinsfile_CNP
All `-nonprod.json` files are now excluded on staging and preview to ensure we deploy and test production version of CCD definition.
```
[ ] Yes
[x] No
```
=> build: excluded -nonprod.json files from definition on preview and staging

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ResubmitClaimCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/ResubmitClaimCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1628
-Standardised the confirmation pages by removing the "What happens next" text from confirmation pages
```
[ ] Yes
[x] No
```
=> refactor: remove "What happens next" from confirmation pages (CMC-1628) (2/2)

build.gradle
Reverts hmcts/civil-service#51
Causing issues with master build:  
[Fatal Error] spring-statemachine-core-3.0.0.M2.pom:7:3: The element type "hr" must be terminated by the matching end-tag "</hr>"
=> Revert "build(deps): bump spring-security-core from 5.4.6 to 5.5.0"

src/contractTest/java/uk/gov/hmcts/reform/civil/RpaConsumerTest.java, src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java, src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowFlag.java, src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java, src/test/java/uk/gov/hmcts/reform/civil/aspect/EventAllowedAspectTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/robotics/NotifyRoboticsOnCaseHandedOfflineHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/PaymentTaskHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/StartBusinessProcessTaskHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/RepresentativeServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapperTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperTest.java
https://tools.hmcts.net/jira/browse/CMC-1692
Example flow flag use in Camunda expression: `${!empty flowFlags.RPA_CONTINUOUS_FEED}`
```
[ ] Yes
[x] No
```
=> feat: added RPA_CONTINUOUS_FEED flow flag to state flow engine (CMC-1692)

build.gradle, sendgrid-client/build.gradle
https://tools.hmcts.net/jira/browse/CMC-1684
Bump the backlog of dependabot PRs.
This covers PRs #48, #50, #66, #67, #68, #69, #71, #74, #76, #78, #79, #81, #84, #85, #87, #91, #101, #104, #108, #109, #110, and #116.
```
[ ] Yes
[x] No
```
=> fix: Bump dependencies (CMC-1684)

src/main/resources/schema/rpa-json-schema.json
Allowing address line to have up to 60 char length in RPA mapping.
```
[ ] Yes
[ ] No
```
=> Increment allowed address line length for RPA to 60

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateCallbackHandlerTest.java
Business process should be set to READY (and therefore triggered on submitted callback) only for respondent 1, as Camunda diagram contains notification only for 1v1 cases.
```
[ ] Yes
[x] No
```
=> fix: business process set to ready only for respondent 1 (CMC-1348)

src/main/java/uk/gov/hmcts/reform/civil/validation/ValidateEmailService.java, src/test/java/uk/gov/hmcts/reform/civil/validation/ValidateEmailServiceTest.java
https://tools.hmcts.net/jira/browse/CMC-1718
Validate emails with:
- dot at beginning of username
- dot at end of username
- username larger than 64 characters
```
[ ] Yes
[x] No
```
=> fix: further validation for emails (CMC-1718)

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1348
Set response deadlines for both defendants when solicitor represents both and completes extension request
```
[ ] Yes
[x] No
```
=> feat: update both response deadlines when extension (CMC-1348)

.dependabot/config.yml
n/a
- Changing depandabot to update weekly rather than daily, using less PR resources
```
[ ] Yes
[x] No
```
=> fix: change dependabot to update weekly

infrastructure/main.tf
N/A
Remove terraform entry for cmc-db-password as superseded by cmc-db-password-v11
```
[ ] Yes
[X] No
```
=> Chore: Remove terraform entry for cmc-db-password as superseded by cmc-db-password-v11

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
2021-12-01T16:04:04.899 INFO [http-nio-4000-exec-4] u.g.h.r.c.s.d.SecuredDocumentManagementService Uploading file sealed_claim_form_000DC015.pdf2021-12-01T16:04:04.899 INFO [http-nio-4000-exec-4] u.g.h.r.c.s.d.SecuredDocumentManagementService Uploading file sealed_claim_form_000DC015.pdf2021-12-01T16:04:05.276 ERROR [TopicSubscriptionManager] u.g.hmcts.reform.civil.stateflow.StateFlowListener Ambiguous transitions permitting state [MAIN.CLAIM_ISSUED_PAYMENT_SUCCESSFUL] to move to more than one next states [MAIN.PENDING_CLAIM_ISSUED,MAIN.PENDING_CLAIM_ISSUED_UNREGISTERED_DEFENDANT].2021-12-01T16:04:05.277
```
[ ] Yes
[x] No
```
=> Fix State flow listener ambiguous transitions

src/contractTest/java/uk/gov/hmcts/reform/civil/RpaConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/civil/RpaContinuousFeedConsumerTest.java, src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/AssignCaseSupportController.java, src/main/java/uk/gov/hmcts/reform/civil/service/CoreCaseDataService.java, src/main/java/uk/gov/hmcts/reform/civil/service/CoreCaseUserService.java, src/main/java/uk/gov/hmcts/reform/civil/service/OrganisationService.java, src/main/java/uk/gov/hmcts/reform/civil/service/UserService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/civil/service/CoreCaseDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/CoreCaseUserServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/OrganisationServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/UserServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperTest.java
https://tools.hmcts.net/jira/browse/CMC-1873
**Root cause:** From E2E we check for ongoing business process for every event with max retries of 300. For every retry you  make a call to idam to get access token causing idam flooded with civil service calls. So, caching idam access token for 60min per user.
=> Move idam calls to cache - its blocking master with 429 failures in logs 

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1931
Changing logic for setting the multi party flag which is used for field / page show conditions in defendant response journey
- Logic Updated for the mid event
- It now takes into consideration the current user that is running the event. As this will enable us to see if they have just gave a FULL DEFENCE response to show additional screens
- Bug was raised as Respondent 1 could have said Full Defence, old logic would have resuled as TRUE for respondent 2. By checking the additional parameter of isRespondent1 we can identify the user who is currently running the event 
- Tests updated / refactored
```
[ ] Yes
[x] No
```
=> fix/CMC-1931: CaseFlag updated to now check for that users response

src/main/java/uk/gov/hmcts/reform/civil/model/Party.java, src/test/java/uk/gov/hmcts/reform/civil/utils/DocmosisTemplateDataUtilsTest.java
https://tools.hmcts.net/jira/browse/CMC-1959
The PR enables the update of partyName field in caseData when applicant or respondent name is updated during claim creation.
the effect is observed in the Claim form that is sent out.
```
[ ] Yes
[ x] No
```
=> fix: update partyname field in casedata when appl or def name is changed

charts/civil-service/Chart.yaml
- Bump java charts to v3.7.2
- Bump camunda-bpm to 0.0.23
N/A
```
[ ] Yes
[x] No
```
=> build/bump-charts: Update java charts to v3.7.2

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CMC-1974
Added a check for same solicitor and if any of the respondents response is full defence:
_1v2 Same solicitor
For defendant 1 chose Response: Admit claim
For defendant 2 chose Response: Reject claim_
MultiPartyResponseTypeFlags should be FULL_DEFENCE, so solicitor is able to fill in the DQs. Hence there won't be a null pointer exception.
```
[] Yes
[x] No
```
=> bugfix/CMC-1974 Null pointer exception on generating DQ

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1967
Fix to show document link under correct heading in Claim Documents tab
```
[ ] Yes
[x] No
```
=> fix: show document link under correct heading in Claim Documents

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentsCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentsCallbackHandlerTest.java
N/A
- Move V1 callback to V0 
- CCD currently points to V1 callback, which will default to V0
```
[ ] Yes
[x] No
```
=> refactor: remove V1 callback to V0 in the PaymentsCallbackHandler (1/2)

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/BaseCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CMC-1985
Retain solicitor references otherwise lost in defendant response journey (1v2 diff solicitor). solicitorReferences (which contains applicant solicitor reference and defendant 1 solicitor reference) was being set to null when defendant 2 responded. Similarly respondentSolicitor2Reference field was being set to null when defendant 1 was responding.
The change  done is to pick all the solicitor references from the caseDetailsBefore field in callbackParams in the callback handler method for about-to-submit of Defendant Response journey in civil-service.
All the original solicitor references values from the caseDetailsBefore are again set to the about-to-submit casedata so that no reference is lost.
**Does this PR introduce a breaking change?** …
=> feat: retain solicitor references otherwise lost upon defendant response

src/main/java/uk/gov/hmcts/reform/civil/config/LaunchDarklyConfiguration.java
No JIRA
fixed security issue due to System.get(), which could be overridden by an attacker
Attackers can control the file system path argument to get() at LaunchDarklyConfiguration.java line 93, which allows them to access or modify otherwise protected files.Allowing user input to control paths used in file system operations could enable an attacker to access or modify otherwise protected system resources.
```
[ ] Yes
[X] No
```
=> fixed security issue

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CMC-2002
```
[ ] Yes
[X] No
```
=> Fix response document appearing under defendant one in 1v2 same solicitor scenario

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentsCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/civil/service/PaymentsService.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentsCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1996
- When we receive 422 and 504s from CCD Data Store API continue along with Payment Failure stateflow, which allows the user to manually retry
```
[ ] Yes
[x] No
```
=> fix: CMC-1996 - Fail payments when we receive 422 and 504s

src/main/java/uk/gov/hmcts/reform/civil/helpers/LocalDateTimeHelper.java, src/main/java/uk/gov/hmcts/reform/civil/service/documentmanagement/SecuredDocumentManagementService.java, src/main/java/uk/gov/hmcts/reform/civil/service/documentmanagement/UnsecuredDocumentManagementService.java, src/test/java/uk/gov/hmcts/reform/civil/helpers/LocalDateTimeHelperTest.java
https://tools.hmcts.net/jira/browse/CMC-2020
- Use docstore response `createdOn` for the document timestamps, instead of generating our own
- Introduce `LocalDateTimeHelper` to convert from UTC for timestamps
```
[ ] Yes
[x] No
```
=> fix: use docstore response for document created time

src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java, src/test/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationServiceTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapperTest.java
https://tools.hmcts.net/jira/browse/CMC-2032
- remove RPA reason text for non misc event
- send 999 event even if there's a full defense response in divergent response scenario
- update test
```
[ ] Yes
[ ] No
```
=> fix/CMC-2032: update rpa text for 1v2 same solictior full defence response

src/main/java/uk/gov/hmcts/reform/civil/model/TimelineOfEventDetails.java, src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/common/SpecifiedParty.java
Individual's Date of Birth was sent with a wrong date format, so the template showed a wrong date
```
[ ] Yes
[X] No
```
=> fix/Individual DoB format when sending to Docmosis was not correct

src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperForSpec.java
LR Spec RPA - Defendant solicitor Email address comes as null in the RPA JSON for 1v2 SS
https://tools.hmcts.net/jira/browse/CIV-3128
LR Spec RPA - Defendant solicitor Email address comes as null in the RPA JSON for 1v2 SS
```
[ ] Yes
[x ] No
```
=> fix CIV-3128, dix the email address for Defendant for RPA JSON

src/main/java/uk/gov/hmcts/reform/civil/utils/PredicateUtils.java, src/test/java/uk/gov/hmcts/reform/civil/utils/PredicateUtilsTest.java
In claim 1v2, same sol, response date is null for defendant 2, but even if the response is divergent, it has been provided. Condition fixed to account for that
```
[ ] Yes
[X] No
```
=> Fix/spec rpauat/1v2ss divergent rpa2

src/main/java/uk/gov/hmcts/reform/civil/model/sdo/JudgementSum.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-3053
This PR gets rid of the 504 error when entering a non integer into the judgementsum field in teh sdo journey.
```
[ ] Yes
[x] No
```
=> get rid of 504 error when inputting non int

bin/variables/load-staging-environment-variables.sh
```2022-08-31T12:23:48.511 WARN  [http-nio-4452-exec-10] u.g.h.ccd.domain.service.callbacks.CallbackService Unable to connect to callback service http://civil-service-staging.service.core-compute-aat.internal/cases/callbacks/about-to-start because of NotFound 404 Not Found: "404 page not found<EOL>"```
```
[ ] Yes
[ ] No
```
=> Update definition placeholder to use https

build.gradle, config/owasp/suppressions.xml
CIV-4857
The package com.google.code.gson:gson before 2.8.9 are vulnerable to Deserialization of Untrusted Data via the writeReplace() method in internal classes, which may lead to DoS attacks.
```
[ ] Yes
[x] No
```
=> Fix CVE-2022-25647

build.gradle, config/owasp/suppressions.xml
Reverting back Fix CVE-2022-25647 #1473
We are seeing camunda error on our logs and reverting this change thinking it would resolve camunda errors.
Fix CVE-2022-25647 #1473
```
[ ] Yes
[ x] No
```
=> reverting back civil-service 1473 PR

charts/civil-service/values.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateClaimFormForSpecCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateClaimFormForSpecHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-5013
-> Linked to: https://tools.hmcts.net/jira/browse/CIV-1880
- Adding in a missed toggle for NoC in spec callback handler for LiP Scenarios
```
[ ] Yes
[x] No
```
=> fix/CIV-1880: Adding NoC toggle into Spec Handler

src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotSuitableSDOCallbackHandlerTest.java
N/A
- Set the nanosecond of the date/time instance to avoid elision of trailing zeroes to cause test errors.
```
[ ] Yes
[x] No
```
=> Fix random test failure

src/main/java/uk/gov/hmcts/reform/civil/config/JacksonConfiguration.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotSuitableSDOCallbackHandlerTest.java
N/A
- Fix: unit test random failure due to date/time conversion
- New: JacksonConfiguration to define how date/time conversion is supposed to be handled by jackson (prevents date/time values to have variable lengths depending on second and microsecond values)
- Other: minor refactor of test class to reduce amount of linting issues
```
[ ] Yes
[x] No
```
=> Fix flaky unit test and refactor

src/main/java/uk/gov/hmcts/reform/civil/service/stitching/BundleRequestExecutor.java, src/test/java/uk/gov/hmcts/reform/civil/service/stitching/BundleRequestExecutorTest.java
N/A
The stitching service uses BundleRequestExecutor to execute its cal. That service, however, is not very good with logging and in some cases it may fail without reporting any useful information in the logs.
This change improves the logging a bit in order to report failing calls without disclosing sensitive data.
```
[ ] Yes
[ ] No
```
=> Improve logging on stitching service

charts/civil-service/Chart.yaml
N/A
- Bump java chart from 4.0.2 -> 4.0.4
```
[ ] Yes
[x] No
```
=> fix/bumping java chart to 4.0.4

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/migration/MigrateCaseDataCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/civil/utils/CaseMigrationUtility.java
there was a bug spotted where there was a respondent dq present and no court was selected. This should migrate the court to a default location. This is a fix for that
```
[ ] Yes
[x ] No
```
=> fixing respondent dq bug

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/migration/MigrateCaseDataCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/civil/utils/CaseMigrationUtility.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/migration/MigrateCaseDataCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
Updating applicant DQ for unspec so that when applicant dq is present the court location gets set from applicant preferred court selected during claim creation journey 
```
[ ] Yes
[x] No
```
=> Applicant DQ changes

config/owasp/suppressions.xml
Temporarily suppressing CVE-2022-3064 and CVE-2021-4235 as latest snakeyaml 1.33 also has these vulnerabilities.
```
[ ] Yes
[X] No
```
=> Suppressing CVE-2022-3064 and CVE-2021-4235

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/StandardDirectionOrderDJ.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/StandardDirectionOrderDJTest.java
https://tools.hmcts.net/jira/browse/CIV-6651
Changing text box contents in DJ trial and disposal screens to include 'This order has been made without a hearing.'
**Trial Screen**
**Disposal Screen**
```
[ ] Yes
[ ] No
```
=> CIV-6651 - DJ screen update for Trial and Disposal

Dockerfile, build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew, src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandlerTest.java
Reverts hmcts/civil-service#2223
Reverting as this is causing issues with AppInsights that are not reported during the build but are clogging the logs.
Demo appears to have the same issue so we'll rework it in Demo before trying another deployment.
=> Revert "CIV-7098 upgrade to Java 17"

src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java, src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
Update states to allow case prog events if SDO journey i.e. case goes into FULL_DEFENCE_PROCEED;
```
[ ] Yes
[x ] No
```
=> Fix for states from SDO flow

.github/renovate.json
https://tools.hmcts.net/jira/browse/CIV-7169
Applied same weekly schedule and concurrency limit as was previously available in Dependabot
```
[ ] Yes
[x] No
```
=> CIV-7169 Renovate weekly schedule and concurrency limit

charts/civil-service/values.preview.template.yaml, config/owasp/suppressions.xml
Suppressing CVE-2022-45688 as this dependency is not being used anywhere
[ ] Yes
[x ] No
```
=> CIV-0000 - Suppressing CVE-2022-45688

src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java, src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
Update flow state for event STANDARD_DIRECTION_ORDER_DJ to allowed it in flowstates 
NOTIFICATION_ACKNOWLEDGED
NOTIFICATION_ACKNOWLEDGED_TIME_EXTENSION
CLAIM_DETAILS_NOTIFIED_TIME_EXTENSION
previously, for claims going into flow states above,  the event STANDARD_DIRECTION_ORDER_DJ was not allowed, so case could not proceed
https://tools.hmcts.net/jira/browse/CIV-7564
```
[ ] Yes
[x ] No
```
=> CIV-0000 update flow state allowing for STANDARD_DIRECTION_ORDER_DJ

.git-config/hooks/commit-msg, README.md
CIV-7682
The enforcement of git conventions was getting in the way of local merges. This should fix it.
Also some small improvements to the documentation.
```
[ ] Yes
[x] No
```
=> CIV-7682 Fix git convention enforcement for merge

.git-config/hooks/commit-msg
CIV-7682
- Fixed a wrong instruction
- Added support for revert message
```
[ ] Yes
[x] No
```
=> CIV-7682 Fix git conventions

.git-config/hooks/pre-commit, .github/workflows/main.yml
N/A
- Supports "revert-" naming convention for branches, as those branches are created by github automatically
- Supports CIV-TASK in the PR title as it's allowed in commits. Will enable us to stop using CIV-0000 to get around that.
```
[ ] Yes
[x] No
```
=> CIV-TASK Support revert branch naming convention and CIV-TASK

build.gradle
https://tools.hmcts.net/jira/browse/CIV-8005
Sonarqube exclusions removed for PostcodeValidator,BundleRequestExecutor,InformAgreedExtensionDateCallbackHandler
```
[ ] Yes
[x] No
```
=> CIV-8005 Sonarqube exclusions removed 

src/main/java/uk/gov/hmcts/reform/civil/helpers/hearingsmappings/CaseFlagsToHearingValueMapper.java, src/main/java/uk/gov/hmcts/reform/civil/utils/CaseFlagPredicates.java, src/test/java/uk/gov/hmcts/reform/civil/utils/CaseFlagsToHearingValueMapperTest.java
https://tools.hmcts.net/jira/browse/CIV-7927
- Update getInterpreterLanguage to return first first spoken language interpreter subTypeKey (or first sign language subTypeKey when no spoken language is available)
```
[ ] Yes
[x] No
```
=> CIV-7927 Map keys in interpreter language

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadHandlerBase.java
We had previously stored the selection of evidence types, which would show on future retriggers of evidence upload, this is no longer desired.
So we now clear the lists on about to submit
```
[ ] Yes
[ x] No
```
=> CIV-0000 clear evidence selection lists on submission

charts/civil-service/values.preview.template.yaml
CIV-0000 move away from using docker.io images for anything and using hmcts public images.
details in this ticket
https://tools.hmcts.net/jira/browse/DTSPO-14561
```
[ ] Yes
[ x] No
```
=> CIV-0000 move away from using docker.io images

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-10874
Populate hearing notes tab with new notes from assisted order, if assisted order notes exist
```
[ ] Yes
[ x] No
```
=> CIV-10874 hearing notes tab population

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ManageContactInformationCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/ManageContactInformationCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-11422
- Make manage contact information event available for caseworkers in awaiting defendant acknowledgement state
- add a error to stop LRs accessing the event in AWAITING_RESPONDENT_ACKNOWLEDGEMENT
```
[ ] Yes
[x] No
```
=> CIV-11422 Make MCI event available for caseworkers in awaiting defendant acknowledgement state

src/main/java/uk/gov/hmcts/reform/civil/enums/sdo/SmallTrack.java, src/main/java/uk/gov/hmcts/reform/civil/helpers/sdo/SdoHelper.java, src/test/java/uk/gov/hmcts/reform/civil/helpers/sdo/SdoHelperTest.java
[Judge's Screen: Order Details - Dispute Resolution Hearing Section (Small Track SDO) ](https://tools.hmcts.net/jira/browse/CIV-8306)
When a judge is making a Small Claims Track SDO, upon selecting Dispute resolution hearing from the option list, when the judge go to the Order Details screen, the section should be available for the Judge to make the order for Dispute Resolution Hearing.
```
[ ] Yes
[ X] No
```
=> CIV-8306 Dispute Resolution Hearing Small Track SDO

build.gradle
These dependencies were removed because I thought they weren't necessary but removing them introduced intermittent exceptions:
```
2024-04-15T17:33:12.236 ERROR [http-nio-4000-exec-9] o.a.c.c.C.[.[localhost].[/].[dispatcherServlet]java.lang.ClassNotFoundException: com.fasterxml.jackson.module.kotlin.ExtensionsKt
at org.camunda.bpm.extension.rest.config.CamundaFeignExceptionDecoder.decodeException(FeignErrorDecoderConfiguration.kt:84)
at org.camunda.bpm.extension.rest.config.FeignErrorDecoderConfiguration$errorDecoder$1.decode(FeignErrorDecoderConfiguration.kt:61)
at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:98)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:141)
```
It's possible that the dependency set entries are not required …
=> DTSCCI-000 re-add kotlin deps

src/main/java/uk/gov/hmcts/reform/civil/constants/SdoR2UiConstantFastTrack.java, src/main/java/uk/gov/hmcts/reform/civil/constants/SdoR2UiConstantSmallClaim.java, src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandlerTest.java
[CIV-13275 Physical Hearing bundle section (Cosmetic change)](https://tools.hmcts.net/jira/browse/CIV-13725)
Judge's Order Details screen (DRH/NIHL)
Cosmetic change needed on all Judge's Order details screen where the "Physical hearing/trial bundle" section appears.
the default selected option should be "Party" replace the text field content with "The Claimant's solicitor shall bring to the court, on the day of the hearing, a paper copy of the hearing bundle"
```
[ ] Yes
[X] No
```
=> CIV-13275 Physical Hearing bundle section (Cosmetic change)

src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/claimant/UploadHearingDocumentsClaimantScenarioTest.java, src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/defendant/UploadHearingDocumentsDefendantScenarioTest.java, src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/UploadHearingDocumentsClaimantHandler.java, src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/UploadHearingDocumentsDefendantHandler.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/UploadHearingDocumentsClaimantHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/UploadHearingDocumentsDefendantHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15268
Because the hearing documents scenario will now be called from the final orders process, a check is added to ensure that it is only executed when the status is CASE_PROGRESSION.
```
[ ] Yes
[ x ] No
```
=> CIV-15268 hearing documents on further hearing

src/main/java/uk/gov/hmcts/reform/civil/helpers/bundle/BundleRequestMapper.java, src/test/java/uk/gov/hmcts/reform/civil/helpers/bundle/BundleRequestMapperTest.java
https://tools.hmcts.net/jira/browse/CIV-15651
Due to recent changes, Lip v LiP cases now have a duplicate entry for the claimant DQs in the bundle.
```
[ ] Yes
[x] No
```
=> CIV-15651 - remove duplicate entry for LiP DQ in bundles

src/main/java/uk/gov/hmcts/reform/civil/service/FeatureToggleService.java, src/test/java/uk/gov/hmcts/reform/civil/service/FeatureToggleServiceTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-2198
Issue was in unspec LR v Lip claim which can stay online for 14 days waiting for any NoC. If the case happened to be transferred offline via case proceeds in caseman, then we are trying to generate dashboard notificiation and the offline bpmn goes stuck for that case and will not admin to do any actions like adding case note/ manage documents etc.
=> DTSCCI-2198 Dashboard notification flag should be enabled only if it is spec case

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateQueryDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/querymanagement/DocumentQueryMessage.java, src/main/java/uk/gov/hmcts/reform/civil/model/querymanagement/CaseMessage.java, src/main/java/uk/gov/hmcts/reform/civil/service/QueryDocumentGenerator.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateQueryDocumentHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyOtherPartyQueryHasResponseNotificationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/QueryResponseSolicitorNotificationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RaiseQueryCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/civil/model/docmosis/querymanagement/DocumentQueryMessageTest.java, src/test/java/uk/gov/hmcts/reform/civil/model/docmosis/querymanagement/QueryDocumentTest.java, src/test/java/uk/gov/hmcts/reform/civil/model/querymanagement/CaseQueriesCollectionTest.java, src/test/java/uk/gov/hmcts/reform/civil/service/QueryDocumentGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/civil/utils/CaseQueriesUtilTest.java
https://tools.hmcts.net/jira/browse/CIV-17167
Updated CaseMEssage model createdOn field from LocalDateTime to OffsettDateTime to preserve UTC date formatting. Converted the createdOn utc date from UTC to local time for the generated query documents.
```
[ ] Yes
[X] No
```
=> CIV-17167 - Fix Query Document Message Dates

src/main/java/uk/gov/hmcts/reform/civil/helpers/judgmentsonline/DefaultJudgmentOnlineMapper.java, src/main/java/uk/gov/hmcts/reform/civil/helpers/judgmentsonline/JudgmentsOnlineHelper.java, src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java, src/test/java/uk/gov/hmcts/reform/civil/helpers/judgmentsonline/JudgmentsOnlineHelperTest.java
https://tools.hmcts.net/jira/browse/CIV-17629
In DefaultJudgmentOnlineMapper, I have separated the method used to calculate and add the fixed costs and the claim fee into two methods, which now calculate them separately.
The claim fee is added separately to the repayment object, so it is now displayed in the Judgment Tab.
They are also added separately to the totalAmount.
```
[ ] Yes
[ x ] No
```
=> CIV-17629 Claim fee DJ tab

src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudgeDecisionOnReconsiderationRequestCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java, src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardClaimantClaimMatcher.java, src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardDefendantClaimMatcher.java
https://tools.hmcts.net/jira/browse/CIV-17618
Refactored the code to correctly display the Dashboard status after the claimants intention is submitted.
```
[ ] Yes
[x] No
```
=> CIV-17618 - Translation status incorrectly displayed following Claimant Intent
