- src/main/resources/application.yaml
Jira: https://tools.hmcts.net/jira/browse/CMC-1545
changes: remove damages claims from user names
> feat:remove damages claims from user names (cmc-1545)

- src/main/resources/application.yaml
Jira: https://tools.hmcts.net/jira/browse/CMC-1545
changes: remove damages claims from user names
> feat:remove damages claims from user email addresses

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/AcknowledgeClaimApplicantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineApplicantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CreateClaimRespondentNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/RaisingClaimAgainstLitigantInPersonNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimDetailsCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/DeadlinesCalculator.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/AcknowledgeClaimApplicantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineApplicantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CreateClaimRespondentNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/RaisingClaimAgainstLitigantInPersonNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimDetailsCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/DeadlinesCalculatorTest.java
Merging with latest civil-damages master branch
`git remote add civil-damages git@github.com:hmcts/civil-service.git`
`git pull civil-damages master`
- https://github.com/hmcts/civil-ccd-definition/pull/29
- https://github.com/hmcts/civil-camunda-bpmn-definition/pull/12
Master builds for above will create new github releases after functional tests step. This is required for successful build on service master and getting docker image uploaded to ACR.
If ccd-definition or camunda master build fail, they can be run again after this one is merged.
> feat: merge with latest civil-damages master

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationService.java
CMC-1592
Fix to include json keys having nulls.
```
[ ] Yes
[x] No
```
> fix: include keys for null attributes (CMC-1592) 

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
https://tools.hmcts.net/jira/browse/CMC-1573
Move branch to new repo
```
[ ] Yes
[x] No
```
> CMC-1573: Moved Branch code to new Repo

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseProceedsInCasemanRespondentNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseProceedsInCasemanRespondentNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1587
Added hasTransitionedTo check for respondent notification
```
[ ] Yes
[x] No
```
> feat: notify respondent for case offline after notify claim (CMC-1587)

- src/contractTest/java/uk/gov/hmcts/reform/civil/BaseRpaTest.java
Rename pact consumer name to align with other pacts for the same consumer.
> tech: rename pact consumer name (N/A)

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/RepresentativeService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGenerator.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/RepresentativeServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
https://tools.hmcts.net/jira/browse/CMC-1637
remove static claim details and applicant rep details in claim form
```
[ ] Yes
[X] No
```
> fix:resolve static claim details and applicant rep details in claim form

- charts/civil-service/values.aat.template.yaml
- charts/civil-service/values.preview.template.yaml
> build: switched to latest XUI image

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/CMC-1487
```
[ ] Yes
[x] No
```
> build: enabled cross browser and accessibility testing (CMC-1487)

- bin/add-roles.sh
> build: added staff role to env setup script

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/AddDefendantLitigationFriendCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/AddDefendantLitigationFriendCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1595
Added survey link on defendant litigation friend confirmation page.
```
[ ] Yes
[x] No
```
> fix: adding survey link to the defendant litigation friend event (CMC-1595)

- src/contractTest/java/uk/gov/hmcts/reform/civil/RpaConsumerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/AddressBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataEdgeCasesBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataMaxEdgeCasesBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataMinEdgeCasesBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/PartyBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/StatementOfTruthBuilder.java
[CMC-1429](url)
add edge case pacts for RPA.
> tech: add edge case pacts (CMC-1429)

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/DocmosisTemplates.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGeneratorTest.java
https://tools.hmcts.net/jira/browse/CMC-1599
Prefixes either 'claimant' or 'defendant' to the DQ file name depending on the user
```
[ ] Yes
[x] No
```
> fix: Update DQ file name (CMC-1599)

- src/main/java/uk/gov/hmcts/reform/civil/callback/CaseEvent.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseProceedsInCasemanRespondentNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ResubmitClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowState.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseProceedsInCasemanRespondentNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
https://tools.hmcts.net/jira/browse/ROC-9119
> As a LR  who wants to raise a claim on behalf of a claimant
> I want to successfully sign-in to the new LR Specified service
> 
> AND create a new case on behalf of my claimant
> So that I successfully open a specified civil case on behalf of my claimant.
```
[ ] Yes
[x] No
```
> Feature/spec changes ROC-9119

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/BaseExternalTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/PaymentTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/StartBusinessProcessTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/PaymentTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/StartBusinessProcessTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java
https://tools.hmcts.net/jira/browse/CMC-1355
- added multiparty feature flagging
- updated Camunda task handlers to pass flag flag value back to business processes (to allow adding multiparty branches in diagrams)
```
[ ] Yes
[x] No
```
> feat: added feature toggling for multiparty (CMC-1355)

- src/main/java/uk/gov/hmcts/reform/civil/model/ServedDocumentFiles.java
https://tools.hmcts.net/jira/browse/CMC-1528
- remove unused ```medicalReports``` from case data
```
[ ] Yes
[x] No
```
> refactor: remove medicalReports from case data (CMC-1528)

- config/owasp/suppressions.xml
[CMC-1682](url)
Temporary add suppression for Spring library 
```
[ ] Yes
[x] No
```
> fix: temporary add suppression for Spring library (CMC-1682)

- src/main/java/uk/gov/hmcts/reform/civil/stateflow/StateFlow.java
- src/main/java/uk/gov/hmcts/reform/civil/stateflow/StateFlowBuilder.java
- src/main/java/uk/gov/hmcts/reform/civil/stateflow/StateFlowContext.java
- src/main/java/uk/gov/hmcts/reform/civil/stateflow/grammar/OnlyIfNext.java
- src/main/java/uk/gov/hmcts/reform/civil/stateflow/grammar/Set.java
- src/main/java/uk/gov/hmcts/reform/civil/stateflow/grammar/SetNext.java
- src/main/java/uk/gov/hmcts/reform/civil/stateflow/grammar/SubflowNext.java
- src/main/java/uk/gov/hmcts/reform/civil/stateflow/grammar/TransitionToNext.java
- src/main/java/uk/gov/hmcts/reform/civil/stateflow/model/Transition.java
- src/test/java/uk/gov/hmcts/reform/civil/stateflow/StateFlowBuilderTest.java
- src/test/java/uk/gov/hmcts/reform/civil/stateflow/StateFlowTest.java
- src/test/java/uk/gov/hmcts/reform/civil/stateflow/model/TransitionTest.java
https://tools.hmcts.net/jira/browse/CMC-1355
This upgrade of StateFlow Engine offers the capability to set flags on transitions. 
```
[ ] Yes
[X] No
```
> feat: stateflow engine upgrade

- .github/dependabot.yml
https://tools.hmcts.net/jira/browse/CMC-1684
To clear out dependency bump backlog
```
[ ] Yes
[x] No
```
> Increase open PR limit to 50 (CMC-1684)

- Jenkinsfile_nightly
> build: removed unused parameter from nightly pipeline

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1265
(5) Confirmation screen
Change all content to:
Green box: You have submitted the Defendant’s defence
Claim number: 946LR348
Then:
The Claimant legal representative will get a notification to confirm you have provided the Defendant defence. You will be CC’ed.
The Claimant legal representative has until 1 June 2021 to discontinue or proceed with this claim.
```
[ ] Yes
[x] No
```
> refactor: update defendant response confirmation (CMC-1265)

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
Reverts hmcts/civil-service#93
Merged by mistake.
> Revert "refactor: update defendant response confirmation (CMC-1265)"

- bin/pull-latest-release-asset.sh
https://tools.hmcts.net/jira/browse/CMC-1688
Adds retries to pull-latest-release-asset.sh
```
[ ] Yes
[x] No
```
> fix: Add retries to pull-latest-release-asset.sh (CMC-1688)

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1265
(5) Confirmation screen
Change all content to:
Green box: You have submitted the Defendant’s defence
Claim number: 946LR348
Then:
The Claimant legal representative will get a notification to confirm you have provided the Defendant defence. You will be CC’ed.
The Claimant legal representative has until 1 June 2021 to discontinue or proceed with this claim.
```
[ ] Yes
[X] No
```
> refactor: updated client -> client(s) (CMC-1265)

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CMC-1200
Updated confirmation page content, added applicant2 mid event callback and updated model with multiparty case fields.
```
[ ] Yes
[x] No
```
> feat: claim creation for multiparty (CMC-1200)

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/SolicitorServiceAddress.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/RepresentativeService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapper.java
- src/main/java/uk/gov/hmcts/reform/prd/model/ContactInformation.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/RepresentativeServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperTest.java
CMC-1659
Provide org service address for claimant and defendant solicitor
```
[ ] Yes
[ ] No
```
> feat:Provide org service address (CMC-1659)

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1265
Change code and test to match AC on ticket
```
[ ] Yes
[X] No
```
> Fix: CMC-1265: Fix code and test

- bin/pull-latest-release-asset.sh
https://tools.hmcts.net/jira/browse/CMC-1688
`curl` creates an output file whether it's a valid file or not. Changes retry condition to whether the `unzip` command succeeds
```
[ ] Yes
[x] No
```
> fix: Fix retries not working correctly (CMC-1688)

- bin/pull-latest-release-asset.sh
https://tools.hmcts.net/jira/browse/CMC-1688
The fix for this was changed when it was found that the reason the script fails was because the GitHub API calls were being rate limited
`{"message":"API rate limit exceeded for 20.50.109.148. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`
Adding an authentication token to the API call increases the rate limit
```
[ ] Yes
[x] No
```
> fix: Remove retries and add authentication token (CMC-1688)

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1631
```
[ ] Yes
[x] No
```
> fix: standardisation of content (CMC-1631) (2/3)

- build.gradle
https://tools.hmcts.net/jira/browse/CMC-1684
Bumps dependencies. Covers Dependabot PRs: #53, #55, #124, #125, #126, #127, #128, #129, #130.
```
[ ] Yes
[x] No
```
> build(deps): Bump dependencies (CMC-1684)

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CMC-1629
```
[ ] Yes
[x] No
```
> fix: acknowledge claim loses defendant address (CMC-1629) 2/3

- Jenkinsfile_CNP
We need demo branch to be up to date with master in order to apply any infrastructure changes.
```
[ ] Yes
[x] No
```
> build: added pushing to demo from master pipeline

- src/contractTest/java/uk/gov/hmcts/reform/civil/RpaConsumerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/RepresentativeService.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataMaxEdgeCasesBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataMinEdgeCasesBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/RepresentativeServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperTest.java
https://tools.hmcts.net/jira/browse/CMC-1659
RepresentativeService fix + missing unit tests coverage.
```
[ ] Yes
[x] No
```
> fix: correct service address on claim form (CMC-1659)

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/CMC-1662
Add fortify scan on nightly build
```
[ ] Yes
[ ] No
```
> Add fortify scan on nightly build (CMC-1662)

- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/AssignCaseSupportController.java
Updated AssignCaseSupportController with additional case role parameter to support multiparty tests.
```
[ ] Yes
[x] No
```
> test: updated assign case controller with case role parameter

- src/contractTest/java/uk/gov/hmcts/reform/civil/RpaContinuousFeedConsumerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataMaxEdgeCasesBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataMinEdgeCasesBuilder.java
[CMC-1617](https://tools.hmcts.net/jira/browse/CMC-1617)
Add pact tests for inform extension date for RPA continuous feed.
> feat: add pact tests inform extension date for RPA continuous feed (CMC-1617)

- build.gradle
> build: fix CVE-2021-33037 vulnerability

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
n/a
added dimiss claim and take case offline events into new flowstates for when the deadlines have expired but Camunda is yet to act
```
[ ] Yes
[x] No
```
> fix: allow dismiss claim events in flowstate

- README.md
https://tools.hmcts.net/jira/browse/CMC-1728
Adds necessary environment variables and some setup instructions
```
[ ] Yes
[x] No
```
> fix: Update README (CMC-1728)

- charts/civil-service/Chart.yaml
N/A
- Bump java chart version to 3.6.0 
```
[] Yes
[x] No
```
> build: bump java charts to 3.6.0

- src/contractTest/java/uk/gov/hmcts/reform/civil/RpaConsumerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateDirectionsQuestionnaireCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CreateClaimRespondentNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CaseProceedsInCasemanCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDetailsBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicateTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapperTest.java
n/a
removed unnecessary predicates in favour of chaining existing ones in stateflow engine
```
[ ] Yes
[x] No
```
> refactor: removed unnecessary predicates (CMC-NA)

- src/contractTest/java/uk/gov/hmcts/reform/civil/RpaConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/RpaContinuousFeedConsumerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/model/Address.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/AddressLinesMapper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsAddressMapper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/robotics/NotifyRoboticsOnCaseHandedOfflineHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/robotics/NotifyRoboticsOnContinuousFeedHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/AddressLinesMapperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsAddressMapperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperTest.java
[CMC-1708](https://tools.hmcts.net/jira/browse/CMC-1708)
RPA 35 character for address line fix
> feat: RPA 35 character for address line fix (CMC-1708)

- config/owasp/suppressions.xml
N/A
CVE-2020-23171 causing build failure
```
[ ] Yes
[X] No
```
> Fix: suppress CVE-2020-23171 - Related Nim-lang

- src/main/java/uk/gov/hmcts/reform/civil/model/Fee.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGeneratorTest.java
refactor:populate court fee in claim form
```
[ ] Yes
[ ] No
```
> refactor:populate court fee in claim form

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapper.java
This PR fixes the NullPointerException in address mapping of organisation details
> fix: NullPointerException (CMC-NA)

- src/main/java/uk/gov/hmcts/reform/civil/enums/ReasonForProceedingOnPaper.java
https://tools.hmcts.net/jira/browse/CMC-1740
- two new reasons for taking case offline
- RPA treats this field as string so no changes required
```
private String prepareTakenOfflineByStaffReason(ClaimProceedsInCaseman claimProceedsInCaseman) {
if (claimProceedsInCaseman.getReason() == ReasonForProceedingOnPaper.OTHER) {
return claimProceedsInCaseman.getOther();
}
return claimProceedsInCaseman.getReason().name();
}
```
```
[ ] Yes
[x] No
```
> feat: additional take claim offline reasons (CMC-1740) 1/2

- build.gradle
Reverts hmcts/civil-service#304
Breaking Functional tests - needs further investigation
> Revert "build(deps): bump org.springframework.boot from 2.5.2 to 2.5.5"

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicateTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
[CMC-1764](url)
1v2 Same representative - error on create claim - state flow error
> fix: state flow engine error 1v2 same representative

- config/owasp/suppressions.xml
N/A
suppress CVE-2021-22096 until sendgrid update their client software
```
[ ] Yes
[X] No
```
> chore: suppress CVE-2021-22096 until sendgrid update their client software

- build.gradle
- config/owasp/suppressions.xml
N/A
Suppress CVE 2021 22044 until common components update their dependencies
```
[ ] Yes
[ x] No
```
> Chore: Suppress CVE 2021 22044

- Jenkinsfile_nightly
N/A
Further investigation for browser testing required. Green build more important
```
[ ] Yes
[ x] No
```
> Chore: remove xbrowser test - needs further investigation

- security.sh
N/A
Fix security scan issue
```
[ ] Yes
[ ] No
```
> Fix security scan issue

- src/main/java/uk/gov/hmcts/reform/civil/service/postcode/PostcodeLookupService.java
- src/main/java/uk/gov/hmcts/reform/civil/validation/PostcodeValidator.java
> Fixing toUpperCase for nightly build

- charts/civil-service/Chart.yaml
- charts/civil-service/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CCD-2269
Add am-role-assignment-service to preview-aat yml and update hmctspublic version in chart yml
```
[X ] Yes
[ ] No
```
> Feat update helm chart

- bin/utils/ccd-add-role.sh
- charts/civil-service/Chart.yaml
- charts/civil-service/values.aat.template.yaml
- charts/civil-service/values.preview.template.yaml
N/A
Fix for Preview and Master pipelines after Access Management release caused them to fail
```
[ ] Yes
[X] No
```
> Chore: fix preview and master pipelines

- build.gradle
N/A
Upgrade log4j version due to security vulnerability
```
[ ] Yes
[X] No
```
> upgrade log4j due to security vulnerability

- Jenkinsfile_nightly
N/A
Change nightly pipeline execution from approx 5am to approx 6pm
```
[ ] Yes
[X] No
```
> Chore: Change nightly pipeline run to happen at approx 6pm

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- bin/add-roles.sh
N/A
Exclude General Applications (GA) from ccd-definition upload - else it breaks the API tests
```
[ ] Yes
[x] No
```
> Chore: exclude ga ccd definition

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CIV-233
The PR consists of adding the back-end part for giving the reason for why defendent cannot pay immediately.
```
[ ] Yes
[x] No
```
> CIV-233 Adding New Page for Giving Reason Why Not Pay

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
https://tools.hmcts.net/jira/browse/CIV-186
Remove duplication of page in LR Spec Admit part claim journey
```
[ ] Yes
[x] No
```
> feat: rename CaseData field

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/CMC-1860
Re-enabled cross browser test
```
[ ] Yes
[ X] No
```
> enabled x-browser

- build.gradle
N/A
Group numerous dependency updates into 1 PR so as to save on Azure resources
```
[ ] Yes
[X] No
```
> Chore: Group dependancy updates into 1 pr

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
https://tools.hmcts.net/jira/browse/CMC-1826
```
[ ] Yes
[ ] No
```
> fix: CMC 1826 Second defendent legal representative issue

- build.gradle
- sendgrid-client/build.gradle
N/A
Merge PRs 515, 506, 501 & 500 int 1 PR to save on Azure resources
```
[ ] Yes
[ X] No
```
> Chore: Combine numerous dependency PRs into 1 PR

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandlerTest.java
> revert changes to CreateClaimSpecCallbackHandler.java

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CMC-1871
```
[ ] Yes
[ ] No
```
> Cmc 1871 respondent 2 deadline error message

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
> also show error message if respondent1 responds after deadline

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeClaimCallbackHandler.java
https://tools.hmcts.net/jira/browse/CMC-1520
Move about_to_submit v1 to about_to_submit
```
[ ] Yes
[X] No
```
> CMS-1520: replace about_to_submit with v1_about_to_submit, delete v1_about_to_submit

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
N/A
- Moving Defendant Response V1 callback to V0
```
[ ] Yes
[x] No
```
> Clearing up Defendant Response callbacks: V1 to V0

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/AcknowledgeClaimApplicantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/AcknowledgeClaimApplicantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CMC-1913
- Code changes to send email notification in a 1v2 different solicitor scenario
- Added test cases
```
[ ] Yes
[ ] No
```
> CMC-1913: fix for Acknowledge claim 1v2 Email

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
> feat: set and unset isRespondent1 flag in Respond to claim

- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
unit test fix
```
[ ] Yes
[ x] No
```
> fixing unit test

- Jenkinsfile_nightly
- build.gradle
N/A
Add multiparty e2e test to nightly pipeline
```
[ ] Yes
[X] No
```
> Chore: Add multiparty tests to nightly pipeline

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/aos/AcknowledgementOfClaimGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/aos/AcknowledgementOfClaimGeneratorTest.java
> CMC-1914: Litigation friend acknowledge form bug fix

- build.gradle
- charts/civil-service/Chart.yaml
N/A
Upgrade dependencies due to CVE warnings
```
[ ] Yes
[X] No
```
> Chore: upgrade dependencies

- bin/utils/ccd-import-definition.sh
- charts/civil-service/values.aat.template.yaml
N/A
More logging
```
[ ] Yes
[X] No
```
> Test: Add more logging

- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GeneralApplication.java
- src/main/java/uk/gov/hmcts/reform/civil/service/GeneralAppsDeadlinesCalculator.java
- src/main/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppsDeadlinesCalculatorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationServiceTest.java
> notification on submit

- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GeneralApplicationTypes.java
https://tools.hmcts.net/jira/browse/CIV-1344
UI changes as mentioned in Jira
```
[ ] Yes
[X] No
```
> CIV-1344 Add 2 more application types

- src/main/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationService.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/GeneralApplicationDetailsBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-875
Do not include stale InformOtherParty or StatementOfTruth information for consented application.
```
[ ] Yes
[X] No
```
> CIV-875 Request Order With Consent Screen - Applicant Journey

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CMC-1956
Removed redundant cve suppressions
```
[ ] Yes
[ x] No
```
> Removed redundant cve suppressions

- Dockerfile
- audit.json
- build.gradle
- security.sh
https://tools.hmcts.net/jira/browse/CIV-1482
> CIV-1482: Fix security scan & fortify scan

- build.gradle
https://tools.hmcts.net/jira/browse/CIV-1541
> Slim functional test - Run only Api tests

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicateTest.java
https://tools.hmcts.net/jira/browse/CMC-1856
Just to tidy up backward compatibility 
```
[ ] Yes
[x] No
```
> tidy up cmc 1856

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/AddressLinesMapper.java
- src/main/java/uk/gov/hmcts/reform/civil/validation/ValidateEmailService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/AddressLinesMapperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/validation/ValidateEmailServiceTest.java
https://tools.hmcts.net/jira/browse/CMC-1992
https://tools.hmcts.net/jira/browse/CMC-2009
Add additional logic to split address lines by space when required
```
[ ] Yes
[x ] No
```
> RPA address line mapping by space

- src/main/java/uk/gov/hmcts/reform/civil/aspect/EventAllowedAspect.java
- src/test/java/uk/gov/hmcts/reform/civil/aspect/EventAllowedAspectTest.java
https://tools.hmcts.net/jira/browse/CMC-1987
- log current state and state flow history
```
[ ] Yes
[ ] No
```
> add stateFlowHistory to log

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementSpecHandler.java
> CIV-1920- Typo error fixed

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1705
This PR adds claimant2/defendant2 names to the confirmation screen if applicable.
```
[ ] Yes
[x] No
```
> update confirmation screen for multiparty

- config/owasp/suppressions.xml
- security.sh
Fix security scan and dependency check
> Fix security scan and dependency check

- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java
Added feature toggle for Notice of Change feature
```
[ ] Yes
[x ] No
```
> added NOS feature toggle

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/AddressLinesMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/AddressLinesMapperTest.java
https://tools.hmcts.net/jira/browse/CMC-2034
Bug fix to address scenario where one address line is missing
```
[ ] Yes
[x] No
```
> feat: break address lines by space

- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/SealedClaimFormForSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/SealedClaimResponseFormForSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/TimelineEventDetailsDocmosis.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGeneratorForSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimResponseFormGeneratorForSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormForSpecTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
timeline event date appears wrong in the documents
Also, two predicates were valid for the same caseData and that fires an error in FlowState
```
[ ] Yes
[X] No
```
> fix/ timeline event date, FlowState

- src/main/java/uk/gov/hmcts/reform/civil/config/properties/notification/NotificationsProperties.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseCaseHandedOfflineApplicantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseCaseHandedOfflineRespondentNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationData.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseCaseHandedOfflineApplicantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseCaseHandedOfflineRespondentNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1229
The PR contains changes for the Counterclaim journey email flow
```
[ ] Yes
[ ] No
```
> Feat: CIV-1229

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandler.java
> Defect fixes

- src/main/java/uk/gov/hmcts/reform/civil/service/stitching/CivilDocumentStitchingService.java
Adding caseTypeId and jurisdiction in the stitching payload
```
[ ] Yes
[ ] No
```
> Adding caseTypeId and jurisdiction in the stitching payload

- src/main/java/uk/gov/hmcts/reform/CaseDetails.java
- src/main/java/uk/gov/hmcts/reform/civil/model/BundleRequest.java
- src/main/java/uk/gov/hmcts/reform/civil/service/stitching/CivilDocumentStitchingService.java
Stitching api adding CaseDetails.java
```
[ ] Yes
[ ] No
```
> Stitching api adding CaseDetails.java

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/RepresentativeService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGeneratorTest.java
https://tools.hmcts.net/jira/browse/CIV-2365
This PR contains the change on the witness part in the DQ
```
[ ] Yes
[ ] No
```
> CIV-2365: Incorrect info in default DQ form PDF

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/BreathingSpaceEnterNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseTakenOfflineRespondentNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineRespondentForSpecNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseCaseHandedOfflineRespondentNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/BreathingSpaceEnterNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseTakenOfflineRespondentNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseCaseHandedOfflineRespondentNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/helpers/LocalDateTimeHelperTest.java
> CIV-2355 - sending email to respondent 1 if respondent 2 is null

- src/main/java/uk/gov/hmcts/reform/civil/service/DeadlinesCalculator.java
https://tools.hmcts.net/jira/browse/CIV-2389
```
[ ] Yes
[ ] No
```
> CIV-2389: Confirmation page respond time fix

- src/main/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-1999
CIV-1999 Do not check for second solicitor if both defendants have same legal representative
```
[ ] Yes
[X] No
```
> CIV-1999 Do not check for second solicitor if both defendants have same legal representative

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
This change is for Specific Journey 2v1 Intention to Proceed
```
[ ] Yes
[ ] No
```
> Adding 2v1 Flow for not to Proceed

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
This change is for Specific Journey 1v2 Intention to Proceed
```
[ ] Yes
[ ] No
```
> Adding 1v2 Flow for not to Proceed

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GADetailsRespondentSol.java
https://tools.hmcts.net/jira/browse/CIV-934
A Without Notice application should be hidden from any Legal Reps other than the Applicant
```
[x] Yes
[ ] No
```
> CIV-934 Add Respondent Sol GA Details Collection Model

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandler.java
https://tools.hmcts.net/jira/browse/CIV-2528
```
[ ] Yes
[ ] No
```
> CIV-2528: comment fix

- Jenkinsfile_CNP
- bin/pull-latest-ccd-files.sh
- build.gradle
- charts/civil-service/values.preview.template.yaml
- src/main/resources/application.yaml
Fix CVE-2022-29885
```
[ ] Yes
[ ] No
```
> Fix CVE-2022-29885

- build.gradle
Fixing CVEs - CVE-2022-22971, CVE-2022-22970
```
[ ] Yes
[ ] No
```
> Fixing CVEs - CVE-2022-22971, CVE-2022-22970

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CIV-2602
```
[ ] Yes
[ ] No
```
> CIV-2602: 2v1 vulnerability page fix

- src/main/java/uk/gov/hmcts/reform/civil/config/properties/notification/NotificationsProperties.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantClaimDetailsNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationData.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantClaimDetailsNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-2186
I changed date information to respondent deadline date in DD month YYYY.
I have created a new template named as FEAT/CIV-2186 
https://www.notifications.service.gov.uk/services/a8b1617c-8e15-49aa-a8d3-a27a243f3c45/templates/17151a5a-00b1-48b7-8e45-38a5f20b6ec0 .
Which will replace the old id https://www.notifications.service.gov.uk/services/a8b1617c-8e15-49aa-a8d3-a27a243f3c45/templates/6cce54b7-4cf0-4770-9dca-db1a38226f1e .
```
[ ] Yes
[ x] No
```
> Changed the content of email and respective test

- src/main/java/uk/gov/hmcts/reform/civil/config/properties/notification/NotificationsProperties.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantClaimDetailsNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationData.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantClaimDetailsNotificationHandlerTest.java
Reverts hmcts/civil-service#1012
> Revert "Changed the content of email and respective test"

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationServiceTest.java
Added an additional LD check before sending emails to RPA
```
[ ] Yes
[X] No
```
> NO-JIRA: fixed condition to send RPA notification for spec claims

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/response/confirmation/PartialAdmitPaidFullConfirmationText.java
Fix the null problem
```
[ ] Yes
[x ] No
```
> Fix the null problem

- build.gradle
> fix CVE-2022-22978

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserHandler.java
https://tools.hmcts.net/jira/browse/CIV-2408
```
[ ] Yes
[ ] No
```
> fix for 2408 remove user emails from logs

- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GeneralApplication.java
- src/main/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-2463
Refactor use of string on general app notification deadline
```
[ ] Yes
[x] No
```
> CIV-2463 Refactor use of string on general app notification deadline

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
https://tools.hmcts.net/jira/browse/CIV-3138
This ticket contains changes for RPA in Intention to Proceed journey
```
[ ] Yes
[ ] No
```
> CIV-3138: Update for claimant preferred court

- src/main/java/uk/gov/hmcts/reform/civil/model/robotics/RPABreathingSpace.java
added json formatting for bs
```
[ ] Yes
[X] No
```
> fix/ json format for local date

- src/main/java/uk/gov/hmcts/reform/civil/enums/RespondentResponseTypeSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/AdmitNotProceedConfHeader.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/AdmitNotProceedConfText.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/AdmitProceedConfHeader.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/AdmitProceedConfText.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/DefendNotProceedConfHeader.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/DefendNotProceedConfText.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/DefendProceedConfHeader.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/DefendProceedConfText.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/PartyUtils.java
- src/test/java/uk/gov/hmcts/reform/civil/model/CaseDataTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/utils/PartyUtilsTest.java
RPA Json 2v1
The fields for I2P 2v1 are different between Damages and Spec, which created a bug in the confirmation screen, the RPA Json and several conditions
```
[ ] Yes
[X] No
```
> fix/ bug affecting 2v1 claims I2P

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataParent.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsCreditHire.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsRoadTrafficAccident.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1837
This PR populates the fields added in [this ccd PR](https://github.com/hmcts/civil-ccd-definition/pull/910/files).
```
[ ] Yes
[x] No
```
> populate sdo small claims fields

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateDirectionsQuestionnaireCallbackHandler.java
https://tools.hmcts.net/jira/browse/CIV-2662
The PR contains the change for document showing in I2P
```
[ ] Yes
[ ] No
```
> CIV-2662: Update for I2P document

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGenerator.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
https://tools.hmcts.net/jira/browse/CIV-3157
```
[ ] Yes
[ ] No
```
> CIV-3157: 1v2 dq document fix

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/RaisingClaimAgainstLitigantInPersonForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicateTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapperTest.java
Fix error when creating 1v2 different solicitor spec claim if the defendants are not represented
```
[ ] Yes
[X] No
```
> Fix/spec rpauat/1v2ds unrep

- charts/civil-service/Chart.yaml
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGeneratorTest.java
https://tools.hmcts.net/jira/browse/CIV-2663
The PR contains the update on defendant details generation for claimant DQ
```
[ ] Yes
[ ] No
```
> CIV-2663: 1v2 different sol - I2P Camunda tasks

- charts/civil-service/Chart.yaml
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistorySequencer.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapperTest.java
Change so that a full defence response, when the defendant has fully paid, has event code 49 instead of 50
```
[ ] Yes
[X] No
```
> feat event 49 meaning full defence, all was paid

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
- Added NoC flag to false for unrepresented defendants
```
[ ] Yes
[x] No
```
> fix for unrep by adding noc flag

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
> 2v1 RPA for spec

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesController.java
- src/main/java/uk/gov/hmcts/reform/civil/service/citizenui/CaseEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/citizenui/CaseEventServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-2814
```
[ ] Yes
[ x] No
```
> Civ 2814 get event token

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/DashboardClaimInfo.java
- src/main/java/uk/gov/hmcts/reform/civil/service/claimstore/ClaimStoreService.java
- src/main/java/uk/gov/hmcts/reform/cmc/model/CmcClaim.java
- src/test/java/uk/gov/hmcts/reform/civil/service/claimstore/ClaimStoreServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-2747
fix deserialization formatting for response deadline
```
[ ] Yes
[ ] No
```
> changes required to deserialise deadline date

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
> adding Breathing space events - 1v2 defendant response

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/defaultjudgment/CaseLocation.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementHandlerTest.java
> Case management location

- src/main/java/uk/gov/hmcts/reform/civil/enums/sdo/SmallClaimsTimeEstimate.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataParent.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsDocuments.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsHearing.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsJudgementDeductionValue.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsJudgesRecital.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsNotes.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsPreferredEmail.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsPreferredTelephone.java
- src/main/java/uk/gov/hmcts/reform/civil/model/sdo/SmallClaimsWitnessStatement.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1848
https://tools.hmcts.net/jira/browse/CIV-1839
https://tools.hmcts.net/jira/browse/CIV-3009
This PR prepopulates the small claims page as well as some fast track page revision inside the sdo journey
```
[ ] Yes
[x] No
```
> add rest of small claims

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesController.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/dto/EventDto.java
- src/main/java/uk/gov/hmcts/reform/civil/service/CoreCaseDataService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/citizen/events/CaseEventService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/citizen/events/EventSubmissionParams.java
- src/main/java/uk/gov/hmcts/reform/civil/service/citizenui/DashboardClaimInfoService.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/CaseDataContentConverter.java
- src/test/java/uk/gov/hmcts/reform/civil/service/citizenui/CaseEventServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-2824
```
[ ] Yes
[x ] No
```
> Civ 2824 create api to submit response

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseevents/ClaimIssueCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperTest.java
https://tools.hmcts.net/jira/browse/SNI-1225
I have updated organisation id information so that robotics json get defendent solicitor information as well
```
[ ] Yes
[x ] No
```
> Deft referrence not added on caseman RPA issue

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
> Add location name

- src/main/java/uk/gov/hmcts/reform/civil/service/referencedata/LocationRefDataService.java
fetch only courts with court_type_id 10 for civils
```
[ ] Yes
[ X] No
```
> Include case type ID 10 for civil locations

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/AddDefendantLitigationFriendCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDetailsBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicateTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
https://tools.hmcts.net/jira/browse/SNI-1357
- check if org registered when checking if respondents are represented
- update tests
```
[ ] Yes
[ ] No
```
> sni-1357: update predicate to check if org registered for represented defendants

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesController.java
- src/main/java/uk/gov/hmcts/reform/civil/service/citizenui/responsedeadline/DeadlineExtensionCalculatorService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/citizenui/responsedeadline/DeadlineExtensionCalculatorServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-916
```
[ ] Yes
[ ] No
```
> Civ 916 calculate response deadline

- bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-3508)
Added GS_profile role
```
[ ] Yes
[x ] No
```
> Added GS_profile role

- src/main/java/uk/gov/hmcts/reform/civil/service/stitching/CivilDocumentStitchingService.java
> Removed logging

- src/main/java/uk/gov/hmcts/reform/civil/service/stitching/CivilDocumentStitchingService.java
Remove logging case details
```
[ ] Yes
[ ] No
```
> Remove logging case details

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapper.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/OrgPolicyUtils.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/utils/OrgPolicyUtilsTest.java
https://tools.hmcts.net/jira/browse/SNI-1235
Added logic to handle removal of organisation policy when creation of case is happening. And adding litigant solicitor information for id 002
```
[ ] Yes
[x ] No
```
> Added solicitor information for 002_litigant

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
https://tools.hmcts.net/jira/browse/CIV-3798
Fixed unspec claims getting stuck at make pba payment
```
[ ] Yes
[X] No
```
> Fixed unspec 2v1 claims getting stuck at make pba payment

- charts/civil-service/Chart.yaml
> bump ccd chart to 8.0.17

- src/main/java/uk/gov/hmcts/reform/civil/model/Party.java
https://tools.hmcts.net/jira/browse/CIV-3660
This PR contains changes for adding a new email field to send email to respondent when there is no legal representative.
```
[ ] Yes
[ ] No
```
> CIV-3660: Add changes email of respondent

- bin/variables/load-staging-environment-variables.sh
- charts/civil-service/values.aat.template.yaml
> Fix master pipelines

- Jenkinsfile_CNP
> Ignore ssl during tests

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/PollingEventEmitterHandler.java
https://tools.hmcts.net/jira/browse/CIV-4314
Fix Polling Event Emitter in Preview
```
[ ] Yes
[X] No
```
> FIX: CIV-4314 Fix polling event emitter in Preview

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/InterimJudgmentDefendantNotificationHandler.java
https://tools.hmcts.net/jira/projects/CIV/issues/CIV-4581?filter=allissues
```
[ ] Yes
[ x ] No
```
> Fix org of defendant2 bug in notifications

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-3008
Changed the prepopulation callback from a 'mid' to 'about-to-start;.
```
[ ] Yes
[x] No
```
> CIV-3008 Change SDO prepopulation to about-to-start callback

- build.gradle
- config/owasp/suppressions.xml
> Fix CVE-2022-25857

- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-4739
Added a sdo flag
```
[ ] Yes
[ ] No
```
> add sdo flag

- charts/civil-service/Chart.yaml
- charts/civil-service/values.yaml
- src/main/java/uk/gov/hmcts/reform/civil/config/HttpClientConfiguration.java
- src/main/resources/application.yaml
> Fixing the timeout issue

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java
[CIV-4793](https://tools.hmcts.net/jira/browse/CIV-4793)
- Added a court location dynamic list flag
```
[ ] Yes
[x] No
```
> added flag for court locations

- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/TestingSupportController.java
https://tools.hmcts.net/jira/browse/CIV-4793
https://tools.hmcts.net/jira/browse/CIV-3278
- Added feature toggle check needed for api tests
```
[ ] Yes
[x] No
```
> add feature toggle check for api tests

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
> Fix for caseman issue

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-4635 
Fixed flow state for TAKE case offline for listing officer
```
[ ] Yes
[ ] No
```
> Fixed flow state for TAKE case offline for listing officer

- audit.json
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/StandardDirectionOrderDJ.java
Fixed the issue related to SDO DJ
https://tools.hmcts.net/jira/browse/CIV-4635
Changed End  Case state for SDO DJ.
```
[ ] Yes
[ ] No
```
> Changed Case state for SDO DJ.

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-2659
> New branch for 

- build.gradle
N/A
Fix CVE-2022-38752
```
[ ] Yes
[X] No
```
> FIX: CIV-2022-38752

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/StandardDirectionOrderDJ.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/StandardDirectionOrderDJTest.java
https://tools.hmcts.net/jira/browse/CIV-5063
```
[ ] Yes
[ x ] No
```
> CIV-5063 Add CaseManagementLocation to SDO DJ

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CIV-5049
Exclude HNL files on preview as to not impact SDO/DJ with the uplifted changes
```
[ ] Yes
[x] No
```
> fix/exclude HNL files on preview

- config/owasp/suppressions.xml
N/A
Suppress CVE as no fix at this point in time
```
[ ] Yes
[X] No
```
> FIX: suppress CVE due to no fix at this time

- charts/civil-service/Chart.yaml
- charts/civil-service/values.yaml
To set document service only for civil service
```
[ ] Yes
[x] No
```
> Civils to use only secure document service - DM Store

- .github/workflows/stale.yml
updating schedule of stale bot
```
[ ] Yes
[ x] No
```
> updating schedule of stale pr bot

- src/main/java/uk/gov/hmcts/reform/civil/advice/ResourceExceptionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/advice/ResourceExceptionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-5003
StateFlowException added for 500 errors thrown when something is wrong with stateflow as 412
> Added StateFlowException

- src/main/java/uk/gov/hmcts/reform/civil/aspect/EventEmitterAspect.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/BaseExternalTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/PollingEventEmitterHandler.java
CIV-5363
This PR contains following changes -
1. Improving logging around poller, aspect and base external task handler classes.
2. Disabling poller on lower environments.
```
[ ] Yes
[x ] No
```
> Improving Logging for Camunda

- .gitignore
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/state.tf
CIV-5385 
Add Content Type and Source to secret
```
[ ] Yes
[ x ] No
```
> CIV-5385 - Add Content Type and Source to secret

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/InterimJudgmentDefendantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementHandler.java
…r completion of task.
```
[ ] Yes
[ ] No
```
> Changed the State after the end of Camunda flow 

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dj/DefaultJudgmentOrderFormGenerator.java
> CIV4240 Fix for sdo test

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/fees/FeesControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/config/FeesConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/fees/FeesController.java
- src/main/java/uk/gov/hmcts/reform/civil/service/FeesService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/service/FeesServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-5217
Development of endpoints to use the fees api in CUI.
```
[ ] Yes
[X ] No
```
> CIV-5217: Claim Fee and Hearing Fee

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/locations/LocationControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/locations/LocationController.java
https://tools.hmcts.net/jira/browse/CIV-5190
Expose endpoint for court locations
```
[ ] Yes
[ ] No
```
> CIV-5190 expose endpoint for court locations

- src/main/java/uk/gov/hmcts/reform/civil/helpers/LocationHelper.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/helpers/LocationHelperTest.java
epims and region id for ccmcc were swapped
```
[ ] Yes
[X] No
```
> fix, epims and region are swapped

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledHandler.java
> CIV-2324 Case Progression > Hearing Readiness - State Change

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/StartBusinessProcessTaskHandler.java
https://tools.hmcts.net/jira/browse/CIV-5444
Adding log messages for Camunda in case of BpmnError("ABORT");
> added log message

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGeneratorForSpec.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGeneratorForSpecTest.java
N/A
- Fix flaky test SealedClaimFormGeneratorForSpec::generateSealedClaimForm1v2SameSolicitor
- Fix minor typo
```
[ ] Yes
[x] No
```
> Fix flaky unit test

- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGeneratorForSpecTest.java
N/A
- fixed more tests failing due to the time of the day
```
[ ] Yes
[ ] No
```
> Fix more flaky tests

- build.gradle
N/A
- Upgrade of spring-security versions
- Upgrade of tomcat-embedded versions
```
[ ] Yes
[x] No
```
> Upgrade libraries to fix CVE

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandler.java
Fixing master
```
[ ] Yes
[ ] No
```
> Fixing master

- build.gradle
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseevents/ClaimIssueForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseevents/ProceedOfflineForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateAcknowledgementOfClaimForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentsForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeOfServiceCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateForSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/DefendantPinToPostLRspecServiceTest.java
N/A
- Upgrade of jackson version to fix some outstanding issues
```
[ ] Yes
[x] No
```
> Upgrade jackson version

- charts/civil-service/Chart.yaml
- charts/civil-service/values.aat.template.yaml
- charts/civil-service/values.preview.template.yaml
- charts/civil-service/values.yaml
> Move from tags to condition as tags cannot be managed in umberalla charts

- charts/civil-service/values.aat.template.yaml
CIV-5447
Add LD key for Staging. Helm Arrays do not merge they overwrite so need to add this back.
```
[ ] Yes
[x ] No
```
> CIV-5447 - Add LD key for Staging

- audit.json
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandler.java
Spec claim ITP is failing as we are always trying to set casemanagementlocation first then checking if condition and setting again in if condition
> Fixing prod issue introduced by SDO team

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/UpdateFromGACaseEventTaskHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/UpdateFromGACaseEventTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/GeneralApplicationDetailsBuilder.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-5665
Judge makes decision process is getting failed when adding documents to the parent case
- when general application has 2 documents in which 1 document already exists in parent case and again trying to add 2 documents then the process is getting aborted in the middle of camunda process
```
[x ] Yes
[ ] No
```
> CIV-5665 Failure when adding documents to parent case issue fixed

- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/TestingSupportController.java
Added three endpoints which can return event history, flow state and rpa information on the basis of case data.
```
[ ] Yes
[x ] No
```
> Adding methods to get Information for case data

- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java
Addition of new feature toggle which will be used as part of implementing PBAv3
```
[ ] Yes
[x ] No
```
> new feature toggle for PBAv3

- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/TestingSupportController.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataParent.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CIV-3167
Added confirmation screen for CoF
```
[ ] Yes
[X] No
```
Screen shot for new
> Civ 3167 COS green success screen

- build.gradle
- config/owasp/suppressions.xml
Fixing CVE-2022-41946
```
[ ] Yes
[ x] No
```
> Fixing CVE-2022-41946

- src/main/java/uk/gov/hmcts/reform/civil/advice/ResourceExceptionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/advice/ResourceExceptionHandlerTest.java
CIV-5958: Exception (http 500) - NotificationClientException
```
[ ] Yes
[ ] No
```
> CIV-5958: Exception (http 500) - NotificationClientException

- Jenkinsfile_CNP
- config/owasp/suppressions.xml
> SwitchonCos

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGenerator.java
> Fix data in template

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/migration/MigrateCaseDataCallbackHandler.java
> Added more logs for migration utility

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/migration/MigrateCaseDataCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/PollingEventEmitterHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimDetailsCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/PollingEventEmitterHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilderSpec.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilderUnspec.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineSpecTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineUnspecTest.java
https://tools.hmcts.net/jira/browse/CIV-6115
add more test
```
[ ] Yes
[ ] No
```
> CIV-6115 add more test

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CIV-6319
As part fo fix changes introduced in: https://github.com/hmcts/civil-service/pull/1974
```
[ ] Yes
[x] No
```
> fix to Jenkinsfile_CNP

- settings.gradle
> adding plugin management

- src/main/java/uk/gov/hmcts/reform/civil/service/referencedata/LocationRefDataService.java
https://tools.hmcts.net/jira/browse/CIV-6284
```
[ ] Yes
[ ] No
```
> CIV-6296 Sort the court location

- src/main/java/uk/gov/hmcts/reform/civil/config/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/CIV-6703
- Adding NoC roles (used by ccd/aac api) to be able to call the service
```
[ ] Yes
[x] No
```
> CIV-6703: Adding NoC roles to call civil-service for aac

- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
Change pinInPost to false on featureToggleService
```
[ ] Yes
[X] No
```
> Change pinInPost to false - FeatureToggleService

- build.gradle
- src/test/java/uk/gov/hmcts/reform/civil/config/LaunchDarklyConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseevents/ApplicationClosedUpdateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseevents/ApplicationOfflineUpdateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseevents/TriggerApplicationClosureCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseevents/TriggerMoveApplicationOfflineCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseevents/ValidateFeeForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateClaimFormForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/AcknowledgementClaimApplicantForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/AgreedExtensionDateApplicantForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/BreathingSpaceEnterNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseTakenOfflineForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineApplicantForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineRespondentForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineRespondentPartyForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/FailedPaymentApplicantForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/RaisingClaimAgainstLitigantInPersonForSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/EnterBreathingSpaceSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/LiftBreathingSpaceSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/CaseDataToTextGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GenAppStateHelperServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/DirectionsQuestionnaireGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormForSpecTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimResponseFormGeneratorForSpecTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperForSpecTest.java
- src/test/java/uk/gov/hmcts/reform/civil/validation/interfaces/DefendantAddressValidatorTest.java
This PR will fix the PR pipelines failing.
> Fix failing dependency for PR failures

- Jenkinsfile_CNP
CIV-6644
- Always clears the pods regardless of success or failure
- Bonus: observes "enableHelm" label to prevent deletion of pods on success if so desired
```
[ ] Yes
[x] No
```
> Clear pods always and enableHelm

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandlerTest.java
Fix to allow spec cases to continue with RPA - currently ccd cannot find court location info.
```
[ ] Yes
[x] No
```
> re-added callbacks and changed version for spec cases

- Jenkinsfile_CNP
> point civil services to master branch

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementSpecHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/RegistrationInformation.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementSpecHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-7006
Set registration information when judgment is granted specified
```
[ ] Yes
[x ] No
```
> CIV-7006 registration information for judgments

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/NoticeOfChangeRequestCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NoticeOfChangeRequestCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-6662
Adding checks for invalid NoC case states and tests
```
[ ] Yes
[X] No
```
> CIV-6662 Adding Invalid NoC Case States 

- infrastructure/tf-app-insights.tf
[CIV-7098](https://tools.hmcts.net/jira/browse/CIV-7098)
Add App Insights Connection String
```
[ ] Yes
[ x ] No
```
> CIV-7098 - Add App Insights Connection String

- .github/CODEOWNERS
- .github/workflows/main.yml
CIV-5433
Add codeowners 
PR title validation
```
[ ] Yes
[ x ] No
```
> CIV-5433 - Add codeowners and PR title validation

- charts/civil-service/Chart.yaml
- charts/civil-service/values.aat.template.yaml
> CIV-0000 Helm upgrade (not a real ticket number)

- charts/civil-service/values.preview.template.yaml
- add autoscaling config for preview
```
[ ] Yes
[ ] No
```
> CIV-0000 Add autoscaling config for preview

- src/main/java/uk/gov/hmcts/reform/civil/enums/caseprogression/EvidenceUploadFiles.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadApplicantHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadHandlerBase.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadRespondentHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/event/BundleCreationTriggerEventHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadApplicantHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadRespondentHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-6993
Display documents uploaded after bundle is created in bundles Tab
```
[ ] Yes
[ ] No
```
> initial commit for bundle tab changes

- config/owasp/suppressions.xml
N/A
Temporarily suppressing a CVE
```
[ ] Yes
[x] No
```
> CIV-0000 Temporary suppression

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimDismissedRespondentNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/NotificationUtils.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimDismissedRespondentNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-7321
```
[ ] Yes
[ ] No
```
> CIV-7321 Check if respondent is LiP before sending notification

- charts/civil-service/Chart.yaml
N/A
- Bumping civil-service chart version to 0.0.32
```
[ ] Yes
[x] No
```
> CIV-0000 - bump civil-service chart version to 0.0.32

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadApplicantHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadHandlerBase.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadRespondentHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/event/BundleCreationTriggerEventHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/helpers/BundleRequestMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadApplicantHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadRespondentHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/event/BundleCreationTriggerEventHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-6352
EvidenceUploadApplicantHandler.java - Fix for Short circuiting
EvidenceUploadHandlerBase.java -  Fix for Short circuiting
EvidenceUploadRespondentHandler.java - Fix for Short circuiting
BundleCreationTriggerEventHandler.java -Fix for Short circuiting and added one filter to filter bundles with null bundlehearingdate (could be possible as same case data object is used by other existing civil stitching service)
BundleRequestMapper.java - Fix for Short circuiting and one if condition
EvidenceUploadApplicantHandlerTest.java - Fix tests
EvidenceUploadRespondentHandlerTest.java - Fix tests
```
[ ] Yes
[ ] No
```
> CIV-6352 fix shortcircuiting issue

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandlerTest.java
> CIV-6955 Add removed pba flags

- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledHandlerTest.java
CIV-7643
Added unit test
```
[ ] Yes
[x] No
```
> CIV-7643 unit-tests for #2454

- commons-civil/src/main/java/uk/gov/hmcts/reform/civil/helpers/LocalDateTimeHelper.java
- commons-civil/src/test/java/uk/gov/hmcts/reform/civil/helpers/LocalDateTimeHelperTest.java
https://tools.hmcts.net/jira/browse/CIV-6675
> CIV-6675 fixing day light saving change

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/DocmosisTemplates.java
https://tools.hmcts.net/jira/browse/CIV-7766
fix template name issue - adding .docx
```
[ ] Yes
[X] No
```
> CIV-7766 fix .docx

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/assertion/RoboticsCaseDataAssert.java
updating owningCourtCode to 807
> CIV-0000 updating owningCourtCode to 807

- build.gradle
N/A
Multiple renovate PRs, merged into one to reduce the number of builds.
https://github.com/hmcts/civil-service/pull/2425
https://github.com/hmcts/civil-service/pull/2424
https://github.com/hmcts/civil-service/pull/2432
https://github.com/hmcts/civil-service/pull/2436
```
[ ] Yes
[x] No
```
> Update multiple dependencies

- config/owasp/suppressions.xml
N/A
added new suppression. 
```
[ ] Yes
[x] No
```
> CIV-0000 - Update suppressions.xml

- build.gradle
N/A
Solve CVE
```
[ ] Yes
[x] No
```
> CIV-TASK solve cve

- config/owasp/suppressions.xml
> CIV-0000 increasing the deadline of cve and new commit to fix master

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadJudgeHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/documents/DocumentAndNote.java
- src/main/java/uk/gov/hmcts/reform/civil/model/documents/DocumentWithName.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadJudgeHandlerTest.java
Addition of time stamp to judge case note uploads
https://tools.hmcts.net/jira/browse/CIV-8136
```
[ ] Yes
[ x] No
```
> CIV-8136 time stamp case note

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataParent.java
> CIV-8431 fix merge error

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/proceed/confirmation/PayImmediatelyConfText.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/response/confirmation/PartialAdmitPayImmediatelyConfirmationText.java
https://tools.hmcts.net/jira/browse/CIV-6295
Add ofNullable check to PartialAdmitPayImmediatelyConfirmationText
```
[ ] Yes
[X] No
```
> CIV-6295 add ofNullable check

- src/main/java/uk/gov/hmcts/reform/civil/helpers/hearingsmappings/CaseFlagsToHearingValueMapper.java
- src/main/java/uk/gov/hmcts/reform/civil/model/hearingvalues/IndividualDetailsModel.java
- src/test/java/uk/gov/hmcts/reform/civil/helpers/hearingsmappings/HearingsPartyMapperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/hearings/HearingValuesServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/utils/CaseFlagsToHearingValueMapperTest.java
N/A
https://tools.hmcts.net/jira/browse/CIV-8347 (fixing vulneraibility details)
-fixed vulnerability details from list to string
```
[ ] Yes
[ x] No
```
> CIV-0000 changed vulnerability details from array to string

- src/main/java/uk/gov/hmcts/reform/civil/helpers/hearingsmappings/HearingsPartyMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/helpers/hearingsmappings/HearingsPartyMapperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/hearings/HearingValuesServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-8640
- map org id with party id
- update tests
```
[ ] Yes
[ ] No
```
> CIV-8640 Map party ID with org ID

- src/main/java/uk/gov/hmcts/reform/civil/helpers/hearingsmappings/HearingsPartyMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/helpers/hearingsmappings/HearingsPartyMapperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/hearings/HearingValuesServiceTest.java
N/A
- Setting related parties to return an empty list for ExUI / HMC payload
From:
```
"relatedParties": [{}]
```
To:
```
"relatedParties": []
```
```
[ ] Yes
[x] No
```
> CIV-0000 - Fix related parties in payload

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/AddressLinesMapper.java
> CIV-0000 Update AddressLinesMapper.java

- charts/civil-service/Chart.yaml
- charts/civil-service/values.yaml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/CIV-7995
- add config to values.yaml
```
[ ] Yes
[ ] No
```
> CIV-7995 Add more config

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/DocmosisTemplates.java
CIV-7936
Template name
```
[ ] Yes
[X] No
```
> CIV-7936 sdo fast template fixed

- charts/civil-service/Chart.yaml
- charts/civil-service/values.aat.template.yaml
- charts/civil-service/values.yaml
> CIV-000 Update service request url 

- build.gradle
- config/owasp/suppressions.xml
> Bump dependencycheck plugin version

- src/main/java/uk/gov/hmcts/reform/civil/service/CoreCaseDataService.java
Limit number of cases on CUI dashboard
```
[ ] Yes
[x] No
```
> CIV-0000 Limit cases on CUI Dashboard

- build.gradle
- commons-civil/build.gradle
- config/owasp/suppressions.xml
upgraded guava for CVE issue and added CVE to suppression for launch darkly major upgrade not ready for civil
```
[ ] Yes
[x] No
```
> CIV-0000 upgraded guava for CVE issue and added CVE to suppression for LD

- Jenkinsfile_CNP
> CIV-9285 Update Jenkinsfile_CNP

- Jenkinsfile_CNP
Reverts hmcts/civil-service#2909
> Revert "CIV-9285 Update Jenkinsfile_CNP"

- src/main/resources/schema/rpa-json-schema.json
https://tools.hmcts.net/jira/browse/CIV-7818
Remove the code that added for rpa json schema
```
[ ] Yes
[x] No
```
> CIV-0000 Fix for RPA json schema

- src/main/java/uk/gov/hmcts/reform/civil/service/FeatureToggleService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/FeatureToggleServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-9642
- added new toggle called fast-track-uplifts
```
[ ] Yes
[ ] No
```
> CIV-9642 Added Toggle Fast Track Uplifts

- build.gradle
- src/main/java/uk/gov/hmcts/reform/civil/config/ExternalTaskListenerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/exceptions/CompleteTaskException.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/BaseExternalTaskHandler.java
Add retry on complete task failure for camunda
```
[ ] Yes
[ ] No
```
> CIV-0000 Add retry on complete task failure for camunda

- charts/civil-service/Chart.yaml
- charts/civil-service/values.yaml
- src/main/java/uk/gov/hmcts/reform/civil/config/AsyncHandlerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/config/properties/AsyncHandlerProperties.java
- src/main/java/uk/gov/hmcts/reform/civil/event/HearingNoticeSchedulerTaskEvent.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/event/HearingNoticeSchedulerEventHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/AutomatedHearingNoticeHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/config/AsyncHandlerConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/event/HearingNoticeSchedulerEventHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/AutomatedHearingNoticeHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-6330
-Changed the scheduler to dispatch async tasks
```
[ ] Yes
[X] No
```
> CIV-6330 hearing notice scheduler update

- src/main/resources/application.yaml
Added sync handler values to to application.yml to ensure there are always default values set.
```
[ ] Yes
[X] No
```
> CIV-0000 Set Default Async Handler Values

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
NA
Fixed bug seen during CUI FT.
```
[ ] Yes
[x] No
```
> CIV-0000 - bug fix for FT failure.

- config/owasp/suppressions.xml
CIV-9876
Cleanup CVE issues
```
[ ] Yes
[x] No
```
> CIV-9876 Cleanup CVE issues

- charts/civil-service/values.aat.template.yaml
CIV-0000 removing redundant secrets from aat yaml
```
[ ] Yes
[ ] No
```
> CIV-0000 removing redundant secrets from aat yaml

- config/owasp/suppressions.xml
CIV-9835
Fixed CVE-2021-4235
```
[ ] Yes
[x] No
```
> CIV-9835 Fixed CVE-2021-4235

- .github/workflows/main.yml
CIV-00000 Changing naming pattern for branches
```
[ ] Yes
[ x] No
```
> CIV-00000 Changing naming pattern for branches

- Jenkinsfile_CNP
- build.gradle
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineRespondentPartyForSpecNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/SendSDOBulkPrintService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineRespondentPartyForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/SendSDOBulkPrintServiceTest.java
> CIV-0000 addrecipientsinsendletter

- src/main/java/uk/gov/hmcts/reform/civil/config/ExternalTaskListenerConfiguration.java
Add 60 seconds lockduration to finish task before it gets picked by other client
```
[ ] Yes
[ ] No
```
> CIV-0000 fix-tasklistener

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-10288
Subject Change for the RPA email
```
[ ] Yes
[x] No
```
> CIV-10288 Set Up Email Subject Change for LR v LiP

- build.gradle
- config/owasp/suppressions.xml
Fixing CVE-2023-41080
```
[ ] Yes
[ ] No
```
> CIV-0000 Fixing CVE-2023-41080

- build.gradle
NA
updated civil-common version to latest
```
[ ] Yes
[x] No
```
> CIV-0000 - Update build.gradle.

- src/main/java/uk/gov/hmcts/reform/civil/config/ServiceBusConfiguration.java
Added logging of HMC Message HMCStatus if update is provided in the message.
```
[ ] Yes
[x] No
```
> CIV-0000 Log HMCStatus

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ChangeSolicitorEmailCallbackHandler.java
CIV-8451
check postcode only if there is one
```
[ ] Yes
[X] No
```
> CIV-8451 fixed postcode not caring about mandatory

- charts/civil-service/values.aat.template.yaml
*Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```
> CIV-000 Add missing config for staging

- Jenkinsfile_CNP
- charts/civil-service/values.aat.template.yaml
> CIV-000 Change aac service ingress

- src/main/resources/application.yaml
> CIV-0000 add notification template to application.yaml

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/service/stitching/CivilDocumentStitchingService.java
NA
Fixed response date bug
```
[ ] Yes
[x] No
```
> CIV-0000 -  Response date bug.

- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/ResponseRepaymentDetailsForm.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/SealedClaimLipResponseForm.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/SealedClaimResponseFormForSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimResponseFormGeneratorForSpec.java
> CIV-0000 fix issue with lr v lr sealed response generator

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-10044
Free form dates, now populated to 7 days in future
```
[ ] Yes
[x ] No
```
> CIV-10044 updated date in free form, plus 7 days

- src/main/java/uk/gov/hmcts/reform/civil/model/CourtLocation.java
- src/main/java/uk/gov/hmcts/reform/civil/model/dq/Applicant1DQ.java
- src/main/java/uk/gov/hmcts/reform/civil/model/dq/Applicant2DQ.java
- src/main/java/uk/gov/hmcts/reform/civil/model/dq/DQ.java
- src/main/java/uk/gov/hmcts/reform/civil/model/dq/RemoteHearing.java
- src/main/java/uk/gov/hmcts/reform/civil/model/dq/Respondent1DQ.java
- src/main/java/uk/gov/hmcts/reform/civil/model/dq/Respondent2DQ.java
https://tools.hmcts.net/jira/browse/CIV-3883
https://tools.hmcts.net/jira/browse/CIV-8943
https://tools.hmcts.net/jira/browse/CIV-3955
https://tools.hmcts.net/jira/browse/CIV-8942
Damages :Claimant and Defendant Court location selection screen
```
[ ] Yes
[x] No
```
> CIV-3883 CIV-8942 CIV-3955 and CIV-8942

- build.gradle
- charts/civil-service/Chart.yaml
Ignore java-logging module and update Java chart
```
[ ] Yes
[x ] No
```
> CIV-0000 - Ignore java-logging module and update Java chart

- build.gradle
- config/owasp/suppressions.xml
CVE-2023-5072 suppressed and CVE-2023-44487 fixed
```
[ ] Yes
[x] No
```
> CIV-0000 CVE-2023-5072 suppressed and CVE-2023-44487 fixed

- src/main/java/uk/gov/hmcts/reform/civil/Application.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesController.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/UserRoleCaching.java
> CIV-0000 reverting cache from master

- src/main/java/uk/gov/hmcts/reform/civil/service/FeatureToggleService.java
NA
revert the CUI r2 toggle changes.
```
[ ] Yes
[x] No
```
> CIV-0000 Fixed CUI r2 toggle

- charts/civil-service/Chart.yaml
- charts/civil-service/values.yaml
https://tools.hmcts.net/jira/browse/CIV-10624
```
[ ] Yes
[X] No
```
> CIV-10624 Update values.yaml

- charts/civil-service/Chart.yaml
- charts/civil-service/values.yaml
https://tools.hmcts.net/jira/browse/CIV-10624
Fix
```
[ ] Yes
[X] No
```
> CIV-10624 remove secrets form values.yaml

- src/main/java/uk/gov/hmcts/reform/civil/service/search/TrialReadyCheckSearchService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/search/TrialReadyNotificationSearchService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/search/TrialReadyCheckSearchServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/search/TrialReadyNotificationSearchServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-11414
Updated trial ready WA search services to also pick up cases in hearing readiness.
```
[ ] Yes
[x] No
```
> CIV-11414 - Updated trial ready WA search services

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RequestJudgementByAdmissionForSpecCuiCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/ResponseRepaymentDetailsForm.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/SealedClaimLipResponseForm.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimLipResponseFormGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RequestJudgementByAdmissionForSpecCuiCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimLipResponseFormGeneratorTest.java
https://tools.hmcts.net/jira/browse/CIV-9528
```
[ ] Yes
[ ] No
```
> CIV-9528 Update LR Pay Immediately screen bug fix

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataParent.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-8923
specAoSApplicantCorrespondenceAddressdetails is being updated when defendant updates address
```
[ ] Yes
[x] No
```
> CIV-8923 specAoSApplicantCorrespondenceAddressdetails is being updated when defendant updates address

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataParent.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/UnavailabilityDatesUtils.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandlerTest.java
CIV-8923
revert changes from 8923
```
[ ] Yes
[X] No
```
> CIV-8923 revert

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/StandardDirectionOrderDJ.java
Trying to fix the location name variable picked but work allocation  for CIV-9422
> CIV-9422 removing location name from SDO DJ

- build.gradle
- config/owasp/suppressions.xml
- bump azure core 
```
[ ] Yes
[ ] No
```
> CIV-000 CVE-2023-36052 fix

- Jenkinsfile_CNP
- Point service back to CCD master
```
[ ] Yes
[x] No
```
> CIV-0000 - point ccdBranch back to master

- Jenkinsfile_CNP
remove CUI exclusion from jenkinsCNP
```
[ ] Yes
[X] No
```
> CIV-0000 remove CUI exclusion

- build.gradle
> CIV-0000 upgrade bouncy castle

- src/main/java/uk/gov/hmcts/reform/civil/controllers/cases/CasesController.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationService.java
> CIV-12104 remove case data logs

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CertificateOfService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/NotifyClaimCallbackHandlerTest.java
Reverts hmcts/civil-service#3405
> CIV-10787 update COS notify screen add date deemed served revert

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-11979
> CIV-0000 allow toc

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
> CIV-0000 allowtoc in other state

- src/main/java/uk/gov/hmcts/reform/civil/config/SecurityConfiguration.java
Remove auth check for easier debugging of flow states
> CIV-00000 Add testing support flow state endpoint to auth whitelist

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationData.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/PartialRemissionHWFCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardClaimantClaimMatcher.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardDefendantClaimMatcher.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/Claim.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/DashboardClaimStatus.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/HelpWithFeesDetails.java
- src/main/java/uk/gov/hmcts/reform/civil/service/citizen/HWFFeePaymentOutcomeService.java
- src/main/java/uk/gov/hmcts/reform/cmc/model/CmcClaim.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/PartialRemissionHWFCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdClaimStatusDashboardFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/citizenui/HWFFeePaymentOutcomeServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-12562
Part remission HwF - granted - Claimant notifications
```
[ ] Yes
[x ] No
```
> CIV-12562 Part remission HwF - granted - Claimant notifications

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandler.java
> CIV-0000 fix filghtdelay prod failure

- build.gradle
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-12707
```
[ ] Yes
[x] No
```
> CIV-12707 bilingual more info notification

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandler.java
https://tools.hmcts.net/jira/browse/CIV-12703
```
[ ] Yes
[x] No
```
> CIV-12703 More information notification 

- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardClaimantClaimMatcher.java
https://tools.hmcts.net/jira/browse/CIV-12577
```
[ ] Yes
[x] No
```
> CIV-12577 Dashboard status

- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardClaimantClaimMatcher.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardDefendantClaimMatcher.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/Claim.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/DashboardClaimStatus.java
- src/main/java/uk/gov/hmcts/reform/cmc/model/CmcClaim.java
- src/test/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdClaimStatusDashboardFactoryTest.java
https://tools.hmcts.net/jira/browse/CIV-12906
```
[ ] Yes
[x] No
```
> CIV-12906 Claim issue dashboard status

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/NoRemissionHWFCallbackHandler.java
https://tools.hmcts.net/jira/browse/CIV-12703
```
[ ] Yes
[x] No
```
> CIV-12703 Null check for helfwithfeesdetails

- src/main/java/uk/gov/hmcts/reform/civil/enums/HwFMoreInfoRequiredDocuments.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-12707
```
[ ] Yes
[x] No
```
> CIV-12707 Bilingual documents

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationData.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-12707
```
[ ] Yes
[x] No
```
> CIV-12707 Welsh documents placeholder added

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-12707
```
[ ] Yes
[x] No
```
> CIV-12707 document line seperator

- src/main/java/uk/gov/hmcts/reform/civil/enums/NoRemissionDetailsSummary.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationData.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotifyLiPClaimantHwFOutcomeHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-12703
```
[ ] Yes
[x] No
```
> CIV-12703 Reason Eelsh  trasnlation

- config/owasp/suppressions.xml
CIV-6508
resolve CVE-2021-37533
```
[ ] Yes
[ ] No
```
> CIV-6508 Resolve CVE-2021-37533

- dashboard-notifications/src/main/java/uk/gov/hmcts/reform/dashboard/services/DashboardNotificationService.java
- dashboard-notifications/src/main/java/uk/gov/hmcts/reform/dashboard/services/Time.java
- dashboard-notifications/src/test/java/uk/gov/hmcts/reform/dashboard/services/DashboardNotificationServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-12956
Populate field for createdAt
```
[ ] Yes
[x] No
```
> CIV-12956 - populate field for notification action created at

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementSpecHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/FullRemissionHWFCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/service/JudgementService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowLipPredicate.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementSpecHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/FullRemissionHWFCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/RoboticsNotificationServiceTest.java
> CIV-12752 - recarted PR for civ-12752.

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowLipPredicate.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
Reverts hmcts/civil-service#4124
> Revert "CIV-12776 Camunda error during claimant intention"

- build.gradle
- dashboard-notifications/src/main/java/uk/gov/hmcts/reform/dashboard/entities/DashboardNotificationsEntity.java
- dashboard-notifications/src/main/java/uk/gov/hmcts/reform/dashboard/entities/NotificationActionEntity.java
- dashboard-notifications/src/main/java/uk/gov/hmcts/reform/dashboard/services/DashboardNotificationService.java
- dashboard-notifications/src/test/java/uk/gov/hmcts/reform/dashboard/services/DashboardNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/DashboardBaseIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/RecordNotificationClickControllerTest.java
Resolve memory heap issue and clean data from integration
```
[ ] Yes
[ ] No
```
> CIV-00000 Resolve memory heap issue and clean data from integration

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ManageContactInformationCallbackHandler.java
https://tools.hmcts.net/jira/browse/CIV-12999
update mci admin roles on service
```
[ ] Yes
[ ] No
```
> CIV-12999 Add caseworker-civil-staff for MCI

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowLipPredicate.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
https://tools.hmcts.net/jira/browse/CIV-13298
```
[ ] Yes
[ ] No
```
> CIV-13298 Camunda error during ClaimantIntention Full defence DisputetAll

- .github/renovate.json
> CIV-0000 DTSCCI-78 Update renovate config

- src/main/java/uk/gov/hmcts/reform/civil/handler/RetriggerCasesEventHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/RetriggerCasesEventHandlerTest.java
Fix the deserialization of case data when doing a retrigger. 
From now on use a String rather than an Object.
> DTSCCI-0000 Fix retrigger case data

- src/main/resources/db/migration/V2024_03_20_1347__CIV-13133_defendant_response_full_part_admit_pay_installment_scenario.sql
> CIV-0000 Fix tests 

- build.gradle
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/MediationSuccessfulApplicantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationMediationUnsuccessfulClaimantLRHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/MediationSuccessfulApplicantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationMediationUnsuccessfulClaimantLRHandlerTest.java
> CIV-0000 revert 13306

- bin/import-bpmn-diagram.sh
- bin/utils/ccd-import-definition.sh
remove verbose of camunda upload
```
[ ] Yes
[ ] No
```
> CIV-13426 adding version checks on import ccd

- build.gradle
- charts/civil-service/Chart.yaml
- charts/civil-service/values.yaml
- src/main/java/uk/gov/hmcts/reform/civil/config/MvcConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/CallbackController.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/RequestInterceptor.java
- src/test/java/uk/gov/hmcts/reform/civil/config/MvcConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/civil/controllers/RequestInterceptorTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-77
Add case reference to log messages 
```
[ ] Yes
[ ] No
```
> DTSCCI-077 Add case reference to log messages

- Jenkinsfile_CNP
- bin/wait-for.sh
Avoid uploading roles before def store is ready
> DTSCCI-051 Add wait for definition store in pipeline

- src/main/java/uk/gov/hmcts/reform/civil/config/ExternalTaskListenerConfiguration.java
https://tools.hmcts.net/jira/browse/DTSCCI-17
```
[ ] Yes
[ ] No
```
> DTSCCI-017 fixing lock time and number of tasks fetched per client

- build.gradle
Reverts hmcts/civil-service#4522
> CIV-0000 Revert Update plugin au.com.dius.pact to v4.6.9

- .github/renovate.json
> DTSCCI-000 Update renovate.json

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicateTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapperTest.java
DTSCCI-066
Ambiguous State Errors
```
[ ] Yes
[ ] No
```
> DTSCCI-066 Ambiguous State Errors

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicateTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
DTSCCI-241
```
[ ] Yes
[ ] No
```
> DTSCCI-241 fix for ambigiuous flow state

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicate.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowPredicateTest.java
DTSCCI-267
not suitable for sdo predicate
```
[ ] Yes
[ ] No
```
> DTSCCI-267 not suitable for sdo predicate

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/InterimJudgmentDefendantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/InterimJudgmentDefendantNotificationHandlerTest.java
DTSCCI-337
interim judgement lip respondent org null check
```
[ ] Yes
[ ] No
```
> DTSCCI-337 interim judgement lip respondent org null check

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapperTest.java
DTSCCI-340 case note null check
> DTSCCI-340 case note null check

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateSettlementAgreementFormCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/citizen/UpdateCaseManagementDetailsService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateSettlementAgreementFormCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-13897
https://tools.hmcts.net/jira/browse/CIV-13672
https://tools.hmcts.net/jira/browse/CIV-13967
```
[ ] Yes
[ ] No
```
> CIV-0000 Bulk branch s2 to master

- charts/civil-service/values.aat.template.yaml
- charts/civil-service/values.preview.template.yaml
> CIV-0000 increase xui memory

- src/contractTest/java/uk/gov/hmcts/reform/civil/FeesLookupApiConsumerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-378
```
[ ] Yes
[ ] No
```
> DTSCCI-378 removing unused keyword

- src/contractTest/java/uk/gov/hmcts/reform/civil/FeesLookupApiConsumerTest.java
Reverts hmcts/civil-service#4988
> DTSCCI-378 revert removing unused keyword

- src/main/resources/db/migration/V2024_03_15_1456__CIV-13115_defendant_response_admit_pay_immediately_claimant_scenario.sql
- src/main/resources/db/migration/V2024_03_18_1002__CIV-13116_defendant_response_part_admit_claimant.sql
- src/main/resources/db/migration/V2024_03_21_1145__CIV-13129_defendant_admit_pay_by_date_scenario.sql
- src/main/resources/db/migration/V2024_03_21_1157__CIV-13130_defendant_response_admit_pay_by_instalments_scenario.sql
- src/main/resources/db/migration/V2024_03_21_1216__CIV-13163-defendant-states-paid-scenario.sql
- src/main/resources/db/migration/V2024_03_25_1606__CIV-13201_response_deadline_not_responded.sql
- src/main/resources/db/migration/V2024_03_26_1145__CIV-13199_defendant_full_defence_full_dispute_mediation.sql
- src/main/resources/db/migration/V2024_03_26_1400__CIV-13202_response_deadline_not_responded_defendant_scenario.sql
- src/main/resources/db/migration/V2024_05_09_1531__CIV-13498.defendant_response_bilingual_claimant.sql
https://tools.hmcts.net/jira/browse/CIV-13735
```
[ ] Yes
[ ] No
```
> CIV-13735 -  Incorrect Notification

- src/contractTest/java/uk/gov/hmcts/reform/civil/CaseAssignmentApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcClaimsForClaimantApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcClaimsForDefendantApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcDefendantLinkedApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/NewBundleApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/StitchBundleApiConsumerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-378
```
[ ] Yes
[ ] No
```
> DTSCCI-378 refactoring cmc consumer tests

- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcClaimsForClaimantApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcClaimsForDefendantApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcConsumerTestUtil.java
- src/main/java/uk/gov/hmcts/reform/cmc/model/CmcClaim.java
https://tools.hmcts.net/jira/browse/DTSCCI-378
```
[ ] Yes
[ ] No
```
> DTSCCI-378 refactoring consumer tests

- src/main/java/uk/gov/hmcts/reform/civil/helpers/SettleClaimHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/SettleClaimMarkPaidFullCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/helpers/SettleClaimHelperTest.java
> CIV-14279 Refactoring - CCD event: Settle this claim - remove 1v2 same LR assumption

- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcClaimsForClaimantApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcClaimsForDefendantApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcConsumerTestUtil.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/CmcDefendantLinkedApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/FeesRangeGroupApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/NewBundleApiConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/civil/StitchBundleApiConsumerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-508
```
[ ] Yes
[ ] No
```
> DTSCCI-508 adding state to consumer tests

- src/main/resources/db/migration/V2024_03_15_1445__CIV-13077_defendant_orgorltdcompany_admit_pay_by_date_scenario.sql
- src/main/resources/db/migration/V2024_03_15_1456__CIV-13115_defendant_response_admit_pay_immediately_claimant_scenario.sql
- src/main/resources/db/migration/V2024_03_18_1002__CIV-13116_defendant_response_part_admit_claimant.sql
- src/main/resources/db/migration/V2024_03_18_1456__CIV-13111_defendant_response_full_part_admit_installments_org_com_claimant_scenario.sql
- src/main/resources/db/migration/V2024_03_20_1231__CIV-13140_claimant_states_paid_in_full_scenario.sql
- src/main/resources/db/migration/V2024_03_21_1040__CIV-13162_defendant_response_part_admit_pay_already_claimant_scenario.sql
- src/main/resources/db/migration/V2024_03_21_1136__CIV-13164_claimant_full_defence_no_mediation.sql
- src/main/resources/db/migration/V2024_03_21_1145__CIV-13129_defendant_admit_pay_by_date_scenario.sql
- src/main/resources/db/migration/V2024_03_21_1157__CIV-13130_defendant_response_admit_pay_by_instalments_scenario.sql
- src/main/resources/db/migration/V2024_03_26_1145__CIV-13199_defendant_full_defence_full_dispute_mediation.sql
- src/main/resources/db/migration/V2024_03_27_1108__CIV-13165-full-defence-full-dispute-mediation-claimant.sql
- src/main/resources/db/migration/V2024_03_27_1420__CIV-13166-claimant_full_defence_fast_track.sql
… uploaded
https://tools.hmcts.net/jira/browse/CIV-14147
added a notification to delete after translated documents 
```
[ ] Yes
[x] No
```
> CIV-14147 added notification to delete after translated documents 

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineRespondentPartyForSpecNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardDefendantClaimMatcher.java
- src/main/java/uk/gov/hmcts/reform/civil/service/citizenui/DashboardClaimInfoService.java
- src/test/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdClaimStatusDashboardFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/citizenui/DashboardClaimInfoServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-14343
Fix defendant CCJ dashboard status
```
[ ] Yes
[x] No
```
> CIV-14343 Fix defendant CCJ dashboard status

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/helpers/LocationHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateSDOCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/helpers/LocationHelperTest.java
https://tools.hmcts.net/jira/browse/CIV-13825
Update cml when sdo and legal advisor spec under 1000 ccmcc
```
[ ] Yes
[x ] No
```
> CIV-13825 cml sdo legal advisor

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/claimant/DefendantNocScenarioTest.java
- src/main/resources/db/migration/V2024_06_18_1101__CIV-14091_claimant_notification_defendant_noc.sql
Test PR for https://tools.hmcts.net/jira/browse/CIV-14292
> CIV-14292 Notice Of Change

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowLipPredicate.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowState.java
- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngine.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/StateFlowEngineTest.java
https://tools.hmcts.net/jira/browse/CIV-14281
Adding summary to NOC taken offline Defendant Lip to LR
```
[ ] Yes
[x] No
```
> CIV-14281 - Adding summary to Noc taken offline

- build.gradle
> DTSCCI-490 Remove Props Volume lib as dependency

- src/main/java/uk/gov/hmcts/reform/civil/service/FeesPaymentService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/FeesPaymentServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-14696
Prevent rounding in gov payment request
```
[ ] Yes
[x] No
```
> CIV-14696 Prevent rounding in gov payment request

- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineApplicantForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineApplicantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineRespondentForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimContinuingOnlineRespondentPartyForSpecNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimDJNonDivergentClaimantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimDJNonDivergentDefendantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimReconsiderationUpheldClaimantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimReconsiderationUpheldDefendantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimSetAsideJudgmentClaimantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimSetAsideJudgmentDefendantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimantResponseConfirmsToProceedRespondentNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimantResponseNotAgreedRepaymentDefendantLipNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ClaimantResponseNotAgreedRepaymentRespondentNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CreateClaimRespondentNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CreateSDOApplicantsNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CreateSDORespondent1NotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CreateSDORespondent2NotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantChangeOfAddressApplicantForCuiNotificationHandlerTest.java
Remove Spring contexts from Unit tests
https://tools.hmcts.net/jira/browse/DTSCCI-381
Sub Task
https://tools.hmcts.net/jira/browse/DTSCCI-444
Removed Spring contexts from unit tests.
```
[ ] Yes
[ ] No
```
> DTSCCI-444 Remove Spring context

- build.gradle
Reverts hmcts/civil-service#5208
> Revert "Update plugin com.github.hmcts.rse-cft-lib to v0.19.1337"

- src/main/java/uk/gov/hmcts/reform/cmc/model/CmcClaim.java
- src/test/java/uk/gov/hmcts/reform/cmc/model/CmcClaimTest.java
DTSCCI-730
fix payment intention npe
```
[ ] Yes
[ ] No
```
> DTSCCI-730 fix payment intention npe

- src/main/resources/application.yaml
[DTSCCI-779](https://tools.hmcts.net/jira/browse/DTSCCI-779)
Switch on simple state flow engine by default
```
[ ] Yes
[x ] No
```
> DTSCCI-779 Switch on simple state flow engine by default

- src/main/java/uk/gov/hmcts/reform/civil/controllers/cases/CaseAssignmentController.java
> DTSCCI-313 bring back deprecated endpoint for prod

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/defendant/GeneralAppCreatedScenarioTest.java
> CIV-0000 - Update GeneralAppCreatedScenarioTest.java

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementSpecHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementSpecHandlerTest.java
DTSCCI-819
revert
```
[ ] Yes
[ ] No
```
> DTSCCI-819 revert

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataCaseProgression.java
- src/main/java/uk/gov/hmcts/reform/civil/model/finalorders/FinalOrdersComplexityBand.java
https://tools.hmcts.net/jira/browse/CIV-15096
https://tools.hmcts.net/jira/browse/CIV-15097
- Add case fields for final order FT and INT complexity bands
```
[ ] Yes
[ ] No
```
> CIV-15096 CIV-15097 FT and INT complexity band screens final order

- src/main/java/uk/gov/hmcts/reform/civil/enums/caseprogression/FinalOrderDownloadTemplateOptions.java
- src/main/java/uk/gov/hmcts/reform/civil/enums/caseprogression/FinalOrderSelection.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataCaseProgression.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15098
https://tools.hmcts.net/jira/browse/CIV-15099
- add download template options
- add logic to populate template list to download
```
[ ] Yes
[ ] No
```
> CIV-15098 CIV-15099 Final order options and select template screen

- build.gradle
- dashboard-notifications/build.gradle
DTSCCI-845
migrate jcenter references
```
[ ] Yes
[ ] No
```
> DTSCCI-845 migrate jcenter references

- src/main/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-14919
Displaying applications time in a different timezone
```
[ ] Yes
[x] No
```
> CIV-14919 Displaying applications time

- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardClaimantClaimMatcher.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardDefendantClaimMatcher.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/Claim.java
- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/DashboardClaimStatus.java
- src/test/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdClaimStatusDashboardFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/civil/model/citizenui/DashboardClaimStatusFactoryTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-15069
> CIV-15069 Claim Dismissed Dashboard Status

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/applicant/GeneralAppSubmittedScenarioTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/generalapplication/applicant/GeneralApplicationMoreInfoRequiredScenarioTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/generalapplication/respondent/ApplicationUncloakedOrderMadeRespondentScenarioTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/generalapplication/respondent/GeneralApplicationMoreInfoRequiredScenarioTest.java
- src/main/resources/db/migration/V2024_09_02_1230__CIV_14421_general_application_moreInfo_required_applicant.sql
- src/main/resources/db/migration/V2024_09_02_1301__CIV_14421_general_application_moreInfo_required_respondent.sql
- src/main/resources/db/migration/V2024_09_04_1610__CIV-14404-general-application-submitted.sql
- src/main/resources/db/migration/V2024_09_05_1523__CIV-14412_general_application_judge_uncloak_respondent.sql
> CIV-0000 Bulk cui sprint branch 

- src/main/java/uk/gov/hmcts/reform/civil/advice/UncaughtExceptionHandler.java
> DTSCCI-0000 Log exception

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/claimant/DefendantResponseFullAdmitPayImmediatelyClaimantScenarioTest.java
- src/main/resources/db/migration/V2024_03_15_1456__CIV-13115_defendant_response_admit_pay_immediately_claimant_scenario.sql
https://tools.hmcts.net/jira/browse/CIV-15324
Update tell us it's paid link text
```
[ ] Yes
[x] No
```
> CIV-15324 Update tell us it's paid link text

- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/SealedClaimLipResponseForm.java
https://tools.hmcts.net/jira/browse/DTSCCI-911
```
[ ] Yes
[ ] No
```
> DTSCCI-911 protect against null pointer exception

- README.md
…y initialisation issue.
```
[ ] Yes
[ ] No
```
> DTSCCI-000 updating readme for the dev preview setup

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/HearingFeeDueHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/HearingFeeDueHandlerTest.java
Fix toggle logic in hearingFeeDueHandler 
```
[ ] Yes
[ x] No
```
> CIV-0000 hearing fee toggle updates

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/GenerateDirectionOrderCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15142
https://tools.hmcts.net/jira/browse/CIV-15143
- rename uploaded file
- store in CFV
```
[ ] Yes
[ ] No
```
> CIV-15142 CIV-15143 Download link for uploaded order and storage

- infrastructure/state.tf
> CIV-0000 pointing to terraform azurm 2.53 version

- src/main/java/uk/gov/hmcts/reform/civil/utils/InterestCalculator.java
- src/test/java/uk/gov/hmcts/reform/civil/utils/InterestCalculatorTest.java
https://tools.hmcts.net/jira/browse/CIV-15484
refactored interest calculations
```
[ ] Yes
[ ] No
```
> CIV-15484 - Fix to prevent interest from incorrectly accumulating once claim is submitted

- src/main/java/uk/gov/hmcts/reform/civil/stateflow/transitions/DraftTransitionBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/stateflow/transitions/DraftTransitionBuilderTest.java
> CIV-0000 fix for GA flag selection

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationForDefendantRepresented.java
DTSCCI-976
fix npe
```
[ ] Yes
[ ] No
```
> DTSCCI-976 fix npe

- src/main/java/uk/gov/hmcts/reform/civil/model/Fee2Dto.java
- src/main/java/uk/gov/hmcts/reform/civil/model/FeeLookupResponseDto.java
- src/main/java/uk/gov/hmcts/reform/civil/model/FeeVersionDto.java
- src/main/java/uk/gov/hmcts/reform/civil/model/FlatAmountDto.java
- src/main/java/uk/gov/hmcts/reform/civil/model/Jurisdiction1Dto.java
- src/main/java/uk/gov/hmcts/reform/civil/model/Jurisdiction2Dto.java
- src/main/java/uk/gov/hmcts/reform/civil/model/PercentageAmountDto.java
- src/main/java/uk/gov/hmcts/reform/civil/model/VolumeAmountDto.java
- src/main/java/uk/gov/hmcts/reform/cmc/model/BreathingSpace.java
DTSCCI-990
Replace deprecated class to avoid deadlock
```
[ ] Yes
[x] No
```
> DTSCCI-990 replace deprecated class to avoid deadlock

- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/EvidenceConfirmDetails.java
https://tools.hmcts.net/jira/browse/CIV-12317
- add missing annotation
```
[ ] Yes
[ ] No
```
> CIV-12317 Add annotation

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-15619
```
[ ] Yes
[x] No
```
> CIV-15619 - Caseworker unable to add case note

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/ClaimantResponseNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/ClaimantResponseNotificationHandlerTest.java
Reverts hmcts/civil-service#5636
> "CIV-15577 Remove requirement for request CCJ field"

- src/main/java/uk/gov/hmcts/reform/civil/enums/DocCategory.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateDirectionQuestionnaireLipCallBackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateLipClaimFormCallBackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateDirectionQuestionnaireLipCallBackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateLipClaimFormCallBackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15561
Display docs in correct category
```
[ ] Yes
[x] No
```
> CIV-15561 Display docs in correct category

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-15655
Add events to unblock use of bundle creation
```
[ ] Yes
[x] No
```
> CIV-15655 - add asyncStitchComplete + amendBundle to flowstate event allowed

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/CaseProceedOfflineClaimantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/DefendantNocDashboardNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/CaseProceedOfflineDefendantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/CaseProceedOfflineClaimantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/DefendantNocDashboardNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/CaseProceedOfflineDefendantNotificationHandlerTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-15301
> CIV-15301 Deleting All The Previous Notifications When Case Goes Offline

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateCUIResponseSealedFormCallBackHandler.java
DTSCCI-1093
adding log messages
```
[ ] Yes
[ ] No
```
> DTSCCI-1093 adding log messages

- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/common/DebtTemplateData.java
DTSCCI-1093
fix for debit data null check
```
[ ] Yes
[ ] No
```
> DTSCCI-1093 fix for debit data null check

- src/main/java/uk/gov/hmcts/reform/civil/handler/event/StitchingCompleteCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/event/StitchingCompleteCallbackHandlerTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-14890
> CIV-14890 Reset Docs Uploaded After Bundle Once Bundle Is Created

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateCUIResponseSealedFormCallBackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateCUIResponseSealedFormCallBackHandlerTest.java
…q generated
DTSCCI-1085
add response form to system generated documents when no d…
```
[ ] Yes
[ ] No
```
> DTSCCI-1085 add response form to system generated documents 

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateCUIResponseSealedFormCallBackHandler.java
DTSCCI-1085
typo correction in method name
```
[ ] Yes
[ ] No
```
> DTSCCI-1085 typo correction in method name

- src/main/resources/db/migration/V2024_11_05_1414__CIV-15267_update_hearingTaskListOrder.sql
https://tools.hmcts.net/jira/browse/CIV-15267
Documents' task lists change order for defendant when case is in decision outcome
```
[ ] Yes
[x] No
```
> CIV-15267 update Scenario DecisionOutcome

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCuiCallbackHandler.java
https://tools.hmcts.net/jira/browse/DTSCCI-1149
DTSCCI-1149: Add logging
```
[ ] Yes
[ ] No
```
> DTSCCI-1149 Add logging

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/claimant/HearingScheduledClaimantScenarioTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/defendant/HearingScheduledDefendantScenarioTest.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/HearingScheduledClaimantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/HearingScheduledDefendantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/HearingScheduledClaimantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/HearingScheduledDefendantNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15310
Make sure dashboard event & hearing scheduled event use same list
```
[ ] Yes
[x] No
```
> CIV-15310 - update Hearing list for dashboard notification

- build.gradle
> DTSCCI-000 - Make nightly tests run first in civil-service nightly

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCuiCallbackHandler.java
https://tools.hmcts.net/jira/browse/DTSCCI-1149
DTSCCI-1149: Refine logging
```
[ ] Yes
[ ] No
```
> DTSCCI-1149 Refine logging

- src/main/java/uk/gov/hmcts/reform/civil/callback/CaseEvent.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ConfirmOrderReviewCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/ConfirmOrderReviewCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15505
add order confirmation
```
[ ] Yes
[ ] No
```
> CIV-15505 add confirm order review

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/StayCaseClaimantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/StayCaseDefendantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/StayCaseClaimantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/defendant/StayCaseDefendantNotificationHandlerTest.java
PR for https://tools.hmcts.net/jira/browse/CIV-15720
> CIV-15720 Delete Notifications When Case Is Stayed

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/DefendantResponseDeadlineCheckCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/DefendantResponseDeadlineCheckCallbackHandlerTest.java
DTSCCI-1202
fix def res deadline check
added submitted callback to execute everytime.
```
[ ] Yes
[ ] No
```
> DTSCCI-1202 fix def res deadline check

- build.gradle
- src/main/java/uk/gov/hmcts/reform/civil/config/ApplicationConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/config/DocumentGeneratorApplicationConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/config/HttpConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/exceptions/DocumentConversionException.java
- src/main/java/uk/gov/hmcts/reform/civil/service/DocumentConversionService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/DocumentConversionServiceTest.java
DTSCCI-1201 
adding document version service
```
[ ] Yes
[ ] No
```
> DTSCCI-1201 adding document conversion service

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/BundleCreationTriggerHandler.java
N/A
Add logging
```
[ ] Yes
[ ] No
```
> DTSCCI-947 Add logging

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseTakenOfflineApplicantNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseTakenOfflineForSpecApplicantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseTakenOfflineApplicantNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/CaseTakenOfflineForSpecApplicantNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-1248
Fix NPE Caused by not checking for lips
```
[ ] Yes
[ ] No
```
> DTSCCI-1248 - Fix Offline Cases NPE

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CvpJoinLinkSchedulerHandler.java
https://tools.hmcts.net/jira/browse/DTSCCI-1199
Add logging
```
[ ] Yes
[ ] No
```
> DTSCCI-1199 Add logging

- src/main/java/uk/gov/hmcts/reform/civil/helpers/LocationHelper.java
…vel to info
```
[ ] Yes
[ ] No
```
> DTSCCI-1282 LocationHelper updateCaseManagementLocation Change log level

- .github/renovate.json
> DTSCCI-000: change renovate automerge timing

- src/main/java/uk/gov/hmcts/reform/civil/service/mediation/helpers/UnrepresentedLitigantPopulator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/mediation/helpers/UnrepresentedLitigantPopulatorTest.java
DTSCCI-1256
MediationLiPCarm object null check
```
[ ] Yes
[ ] No
```
> DTSCCI-1256: MediationLiPCarm object null check

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/judgmentonline/DefaultJudgmentCoverLetterGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/judgmentonline/DefaultJudgmentCoverLetterGeneratorTest.java
DTSCCI-1182
default judgement cover letter - amend stitch process
```
[ ] Yes
[ ] No
```
> DTSCCI-1182: default judgement cover letter - amend stitch process

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/FeatureToggleService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/FeatureToggleServiceTest.java
Reverts hmcts/civil-service#5879
> Revert "CIV-15576 General Application LiPs - Early adopter courts"

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseDataParent.java
DTSCCI-1353
fix flow-state to allow median un-successful
```
[ ] Yes
[ ] No
```
> DTSCCI-1353: fix flow-state to allow median un-successful

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/DefendantResponseClaimantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/DefendantResponseClaimantNotificationHandlerTest.java
DTSCCI-1355
fix npe on defendent respone cui
```
[ ] Yes
[ ] No
```
> DTSCCI-1355: fix npe on defendent response cui

- src/main/java/uk/gov/hmcts/reform/civil/service/SendFinalOrderBulkPrintService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/SendHearingBulkPrintService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/CoverLetterAppendService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/SendFinalOrderBulkPrintServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/SendHearingBulkPrintServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/CoverLetterAppendServiceTest.java
Reverts hmcts/civil-service#5917
> DTSCCI-1183: cover letter - amend stitch process - revert

- charts/civil-service/values.aat.template.yaml
> DTSCCI-1364: ccd chart upgrade

- src/main/java/uk/gov/hmcts/reform/civil/utils/MediationUtils.java
- src/test/java/uk/gov/hmcts/reform/civil/utils/MediationUtilsTest.java
DTSCCI-1380
npe fix in sdo event
```
[ ] Yes
[ ] No
```
> DTSCCI-1380: npe fix in sdo event

- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/claimform/ClaimFormMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/model/docmosis/claimform/ClaimFormMapperTest.java
DTSCCI-1430
Evidence not pulling through to claim form and response form 
```
[ ] Yes
[ ] No
```
> DTSCCI-1430: Evidence not pulling through to claim form 

- src/main/resources/db/migration/V2025_01_13_1643__CIV-16263-update-description.sql
https://tools.hmcts.net/jira/browse/CIV-16263
Update full stop
```
[ ] Yes
[x] No
```
> CIV-16263 Update full stop

- dashboard-notifications/src/main/java/uk/gov/hmcts/reform/dashboard/services/DashboardNotificationService.java
> DTSCCI-1463 Add logging

- src/main/java/uk/gov/hmcts/reform/civil/service/PaymentsService.java
> DTSCCI-1475: Callback url logged

- src/main/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/flowstate/FlowStateAllowedEventServiceTest.java
DTSCCI-1471
Allow citizen claim issue payment on given flowstate
```
[ ] Yes
[ ] No
```
> DTSCCI-1471: allow citizen claim issue payment on given flowstate

- src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardClaimMatcher.java
- src/test/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdClaimStatusDashboardFactoryTest.java
https://tools.hmcts.net/jira/browse/CIV-16244
Changes to hearing relevant dashboard statuses - extended to support status for HMC hearing scheduling.
```
[ ] Yes
[x] No
```
> CIV-16244 - dashboard status update for AHN case

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/task/respondtoclaimcallbackhandlertasks/UpdateDataRespondentDeadlineResponse.java
> DTSCCI-1479: Fix NullPointer exception

- charts/civil-service/Chart.yaml
- charts/civil-service/values.aat.template.yaml
- charts/civil-service/values.enableHelm.template.yaml
- charts/civil-service/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/reform/civil/service/FeesPaymentService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/UpdatePaymentStatusService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/FeesPaymentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/UpdatePaymentStatusServiceTest.java
DTSCCI-1475
DTSCCI-1475: Add further logging to diagnose payments issue
> DTSCCI-1475: Add further logging to diagnose payments issue

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationDefendantOfHearingHandler.java
https://tools.hmcts.net/jira/browse/DTSCCI-1549
```
[ ] Yes
[ ] No
```
> DTSCCI-1543: Protect against NotificationException

- config/owasp/suppressions.xml
> DTSCCI-000 - Suppress vulnerabilities because no newer version

- dashboard-notifications/src/main/java/uk/gov/hmcts/reform/dashboard/repositories/TaskListRepository.java
- dashboard-notifications/src/main/java/uk/gov/hmcts/reform/dashboard/services/TaskListService.java
- dashboard-notifications/src/test/java/uk/gov/hmcts/reform/dashboard/services/TaskListServiceTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-1620
```
[ ] Yes
[ ] No
```
> DTSCCI-1620 - Return List And Delete Duplicates Notifications

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondQueryCallbackHandler.java
https://tools.hmcts.net/jira/browse/CIV-16666
- temporarily remove business process
```
[ ] Yes
[ ] No
```
> CIV-16666 Remove business process temporarily

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/task/respondtodefencespeccallbackhandlertask/AboutToSubmitRespondToDefenceTask.java
- src/main/java/uk/gov/hmcts/reform/civil/helpers/LocationHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/helpers/LocationHelperTest.java
https://tools.hmcts.net/jira/browse/CIV-16641
Minti lip claims will go/stay at CNBC on claimant intention submission
```
[ ] Yes
[x ] No
```
> CIV-16641 Minti lip claims will go/stay at CNBC on claimant intention submission

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToApplicantSolicitorCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToApplicantSolicitorCallbackHandlerTest.java
> DTSCCI-1699 adding sup data to submitted

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToLipUserHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToLipUserHandlerTest.java
> DTSCCI-1699 revert

- src/main/java/uk/gov/hmcts/reform/civil/utils/HmcDataUtils.java
> DTSCCI-0000 Improve error message

- src/main/java/uk/gov/hmcts/reform/civil/stateflow/transitions/FullDefenceTransitionBuilder.java
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-16843
LipVLR - After Noc, when claim goes to InMediation getting an error
```
[ ] Yes
[x ] No
```
> CIV-16843 updated flow state condition to fix ambiguous error

- infrastructure/ccd-event-service-bus.tf
> DTSCCI-0000 - Disable SB

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/DefaultJudgementSpecHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/InterestCalculator.java
> DTSCCI-1796 Logging

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/SettleClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/SettleClaimCallbackHandlerTest.java
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-16935
Removed about-to-start validation
```
[ ] Yes
[x ] No
```
> CIV-16935 Enable the CW 'Settle this claim' event for LiP claims

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/response/confirmation/PartialAdmitPayImmediatelyConfirmationText.java
https://tools.hmcts.net/jira/browse/CIV-16959
```
[ ] Yes
[ ] No
```
> CIV-16959 LipvLR Confirmation screen has extra text when LR respond 

- charts/civil-service/values.yaml
> DTSCCI-000 - revert keyvault alias

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/DefendantResponseClaimantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/DefendantResponseClaimantNotificationHandlerTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-16970
Create Lip v Lip small claim and link to Defendant Lip
Create a with-consent Vary Order GA as the Claimant Lip
Perform NoC
Login as a LR and respond with Full Admit, Pay by Set Date
Expected results:
Claim should move offline, but existing GAs should be available to view from the 'View Applications' link under the 'Applications' section
**Does this PR introduce a breaking change?** (check one …
> CIV-16970 View Applications Link not available for existing GAs after Case is moved Offline

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/response/confirmation/FullAdmitSetDateConfirmationText.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/response/confirmation/PartialAdmitPayImmediatelyConfirmationText.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/response/confirmation/PartialAdmitSetDateConfirmationText.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/spec/response/confirmation/RepayPlanConfirmationText.java
https://tools.hmcts.net/jira/browse/CIV-16962
Implemented a solution to ensure consistent font size across all elements of the confirmation page.
```
[ ] Yes
[x] No
```
> CIV-16962 - Lip v LR response confirmation screen different sized text - Part Admit Pay By Instalments

- config/owasp/suppressions.xml
Move suppression forward two months
```
[ ] Yes
[ x] No
```
> CIV-0000 move suppression date forward

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/FeatureToggleService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-16952
Allow GA creation when GA for Welsh toggle enabled
```
[ ] Yes
[x] No
```
> CIV-16952 Allow GA creation when GA for Welsh toggle enabled

- src/main/java/uk/gov/hmcts/reform/civil/service/search/TakeCaseOfflineSearchService.java
> DTSCCI-1767: add logs

- bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-17037
Added new role to access profile.
```
[ ] Yes
[x] No
```
> CIV-17037 - Pre-requisite changes for work allocating to WLU 

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseApplicantForCuiNotificationHandler.java
DTSCCI-2073
fix npe on defendant response cui
```
[ ] Yes
[ ] No
```
> DTSCCI-2073: fix npe on defendant response cui

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseApplicantForCuiNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseApplicantForCuiNotificationHandlerTest.java
DTSCCI-2073
fix npe on defendant response cui v1
```
[ ] Yes
[ ] No
```
> DTSCCI-2073: fix npe on defendant response cui v1

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/DefendantResponseClaimantNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/claimant/DefendantResponseClaimantNotificationHandlerTest.java
DTSCCI-2073
fix npe on defendant response cui v2
```
[ ] Yes
[ ] No
```
> DTSCCI-2073: fix npe on defendant response cui v2

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateClaimFormForSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGeneratorForSpec.java
> DTSCCI-1850: adding logs to trace resp1 response deadline

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateCUIResponseSealedFormCallBackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateCUIResponseSealedFormCallBackHandlerTest.java
> CIV-0000 - Fix prod issue

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- bin/run-api-tests.sh
- bin/run-nightly-api-tests.sh
> DTSCCI-2243 Implement failed tests in PR

- src/main/java/uk/gov/hmcts/reform/civil/handler/RetriggerCasesEventHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/RetriggerCasesEventHandlerTest.java
> DTSCCI-000 - Add to final order collection

- src/main/java/uk/gov/hmcts/reform/civil/model/wa/SearchTaskRequest.java
- src/main/java/uk/gov/hmcts/reform/civil/model/wa/SortField.java
- src/main/java/uk/gov/hmcts/reform/civil/model/wa/SortOrder.java
- src/main/java/uk/gov/hmcts/reform/civil/model/wa/SortingParameter.java
- src/main/java/uk/gov/hmcts/reform/civil/service/SendAndReplyMessageService.java
- src/main/resources/application.yaml
> preview wa url

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/task/respondtodefencespeccallbackhandlertask/DetermineNextState.java
- src/main/java/uk/gov/hmcts/reform/civil/service/UpdateClaimStateService.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/CaseStateUtils.java
- src/test/java/uk/gov/hmcts/reform/civil/service/UpdateClaimStateServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/utils/CaseStateUtilsTest.java
> DTSCCI-1945  Full admit Interloc cases incorrectly going into Mediation

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sdo/SdoGeneratorService.java
N/A
Add logging
```
[ ] Yes
[ ] No
```
> DTSCCI-0000 Add logging

- src/main/java/uk/gov/hmcts/reform/civil/notification/handlers/generatehearingnotice/nonhmc/GenerateHearingNoticeAllPartiesEmailGenerator.java
- src/main/java/uk/gov/hmcts/reform/civil/notification/handlers/generatehearingnotice/nonhmc/GenerateHearingNoticeAppSolOneEmailDTOGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/notification/handlers/generatehearingnotice/nonhmc/GenerateHearingNoticeAllPartiesEmailGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/notification/handlers/generatehearingnotice/nonhmc/GenerateHearingNoticeAppSolOneEmailDTOGeneratorTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-2320
> DTSCCI-2320 Update missing properties for notifications

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
> CIV-0000 Remove extra line

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
N/A
update gradle
```
[ ] Yes
[ ] No
```
> DTSCCI-2456 update gradle

- config/owasp/suppressions.xml
> DTSCCI-0000 Add suppressions

- src/main/java/uk/gov/hmcts/reform/civil/handler/RetriggerUpdateLocationDataHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/CoreCaseDataService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/RetriggerUpdateLocationDataHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/CoreCaseDataServiceV2Test.java
> DTSCCI-2427: update res1 dq court location using process

- src/main/java/uk/gov/hmcts/reform/civil/service/search/DefendantResponseDeadlineCheckSearchService.java
https://tools.hmcts.net/jira/browse/DTSCCI-1876
> DTSCCI-1876 Update DefendantResponseDeadlineCheckSearchService.java

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/DocmosisTemplates.java
DTSCCI-2154
Point to old template temporarily
```
[ ] Yes
[ ] No
```
> DTSCCI-2154: Point to old template

- src/main/java/uk/gov/hmcts/reform/civil/utils/InterestCalculator.java
> DTSCCI-2457 Avoid NPE during interest calculation and more logs

- src/main/resources/db/migration/V2025_08_21_1030__CIV-17625_update_part_admit_pay_immediately_scenario.sql
https://tools.hmcts.net/jira/browse/CIV-17625
```
[ ] Yes
[ ] No
```
> CIV-17625 Delete Part Admit Immediately notification

- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/claimantresponse/JudgmentByAdmissionOrDeterminationMapper.java
https://tools.hmcts.net/jira/browse/CIV-17626
- Check if claimant rejects payment type and court agree with claimant payment type
- Check if there is payment date agreed by court
```
[ ] Yes
[ x ] No
```
> CIV-17626 repayment date JO doc

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateForSpecCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateForSpecCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-2651
> DTSCCI-2651 Inform agreed extension was not considering bank holidays while doing error checks for extension

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/InitiateGeneralApplicationService.java
> DTSCCI-2673: adding log messages

- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsDataMapperForSpec.java
> DTSCCI-000: remove log messages

- src/main/java/uk/gov/hmcts/reform/civil/service/dashboardnotifications/Respondent1AdmittedAmountPaymentDeadlineParamsBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/dashboardnotifications/Respondent1AdmittedAmountPaymentDeadlineParamsBuilderTest.java
> DTSCCI-2369 fix for defendant response fully admits pay immediately notification not showing amount

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/respondtoclaimspeccallbackhandlertasks/RespondToClaimSpecCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/dq/DirectionsQuestionnaireForm.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/sealedclaim/SealedClaimResponseFormForSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/builders/DQGeneratorFormBuilder.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dq/helpers/RespondentTemplateForDQGenerator.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimFormGeneratorForSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/SealedClaimResponseFormGeneratorForSpec.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/helpers/StatementOfTruthPopulator.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateClaimSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToDefenceSpecCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/integration/RespondToClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/sealedclaim/helpers/StatementOfTruthPopulatorTest.java
Reverts hmcts/civil-service#7046
> Revert "DTSCCI-2454 Statement of truth is not pulling through for defendant or. claimant LR"
